### ISSUE TITLE
SIGKILL from time to time

### ISSUE THREAD

**Issue by unional** [vercel/turbo#2143]
### What version of Turborepo are you using?

1.5.5

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

It happens on all platforms in GitHub action.

Here is a failed example:

```sh
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /Users/runner/Library/pnpm/store/v3
  Virtual store is at:             node_modules/.pnpm
Progress: resolved 802, reused 19, downloaded 0, added 1
Progress: resolved 802, reused 137, downloaded 0, added [12](https://github.com/unional/standard-log/actions/runs/3167741848/jobs/5158451532#step:5:13)3
Progress: resolved 802, reused 196, downloaded 0, added 189
Progress: resolved 802, reused 294, downloaded 0, added 280
Progress: resolved 802, reused 350, downloaded 0, added 350
Progress: resolved 802, reused 390, downloaded 0, added 387
Progress: resolved 802, reused 474, downloaded 0, added 470
Progress: resolved 802, reused 560, downloaded 0, added 560
Progress: resolved 802, reused 685, downloaded 0, added 710
Progress: resolved 802, reused 760, downloaded 0, added 789
Progress: resolved 802, reused 770, downloaded 0, added 802, done
.../esbuild@0.[15](https://github.com/unional/standard-log/actions/runs/3167741848/jobs/5158451532#step:5:16).10/node_modules/esbuild postinstall$ node install.js
.../.pnpm/turbo@1.5.5/node_modules/turbo postinstall$ node install.js
.../.pnpm/turbo@1.5.5/node_modules/turbo postinstall: node:internal/errors:863
.../.pnpm/turbo@1.5.5/node_modules/turbo postinstall:   const err = new Error(message);
.../.pnpm/turbo@1.5.5/node_modules/turbo postinstall:               ^
.../.pnpm/turbo@1.5.5/node_modules/turbo postinstall: Error: Command failed: /Users/runner/work/standard-log/standard-log/node_modules/.pnpm/turbo@1.5.5/node_modules/turbo/bin/turbo --version
.../.pnpm/turbo@1.5.5/node_modules/turbo postinstall:     at checkExecSyncError (node:child_process:871:11)
.../.pnpm/turbo@1.5.5/node_modules/turbo postinstall:     at Object.execFileSync (node:child_process:907:15)
.../.pnpm/turbo@1.5.5/node_modules/turbo postinstall:     at validateBinaryVersion (/Users/runner/work/standard-log/standard-log/node_modules/.pnpm/turbo@1.5.5/node_modules/turbo/install.js:25:6)
.../.pnpm/turbo@1.5.5/node_modules/turbo postinstall:     at /Users/runner/work/standard-log/standard-log/node_modules/.pnpm/turbo@1.5.5/node_modules/turbo/install.js:308:5 {
.../.pnpm/turbo@1.5.5/node_modules/turbo postinstall:   status: null,
.../.pnpm/turbo@1.5.5/node_modules/turbo postinstall:   signal: 'SIGKILL',
.../.pnpm/turbo@1.5.5/node_modules/turbo postinstall:   output: [ null, Buffer(0) [Uint8Array] [], Buffer(0) [Uint8Array] [] ],
.../.pnpm/turbo@1.5.5/node_modules/turbo postinstall:   pid: 3040,
.../.pnpm/turbo@1.5.5/node_modules/turbo postinstall:   stdout: Buffer(0) [Uint8Array] [],
.../.pnpm/turbo@1.5.5/node_modules/turbo postinstall:   stderr: Buffer(0) [Uint8Array] []
.../.pnpm/turbo@1.5.5/node_modules/turbo postinstall: }
.../.pnpm/turbo@1.5.5/node_modules/turbo postinstall: Node.js v[18](https://github.com/unional/standard-log/actions/runs/3167741848/jobs/5158451532#step:5:19).10.0
.../.pnpm/turbo@1.5.5/node_modules/turbo postinstall: Failed
 ELIFECYCLE  Command failed with exit code 1.
Error: Process completed with exit code 1.
```
https://github.com/unional/standard-log/actions/runs/3167741848/jobs/5158451532

When re-run the jobs again, sometime it will pass.

### Expected Behavior

Should not fail at postinstall

### To Reproduce

It's random, but relatively common.

**Comment by unional** [comment]
https://github.com/unional/standard-log/actions/runs/3167738313

This was failing too, but after retrying 2 times it passes

**Comment by unional** [comment]
https://github.com/unional/clibuilder/actions/runs/3167221106/jobs/5157545003
Another failure, this time on macos node 16

**Comment by qixiaobo** [comment]
Same problem too

**Comment by qixiaobo** [comment]
> Same problem too

https://qiita.com/tatmius/items/05967f4039d13d2b9283

**Comment by anthonyshew** [comment]
Seeing a stale version of `turbo` here so will close. If you're still running into this problem, please open an issue with a reproduction using the most recent canary version.
