### ISSUE TITLE
`libc6-compat` fixes may not be complete in docs and examples

### ISSUE THREAD

**Issue by kriswuollett** [vercel/turbo#2286]
### What version of Turborepo are you using?

1.5.6

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Mac

### Describe the Bug

My app build following the example from `with-docker` fails to build even after adding the `libc6-compat` in the `builder` target in the `Dockerfile` as done as a fix for #2198. See [log.txt](https://github.com/vercel/turborepo/files/9831251/log.txt), or just this snippet here:

```

#20 [installer  7/11] RUN yarn install
#20 sha256:35f5e6dee2888f486318930eb65dc6cb7ce4272c251afd56bf3aa467324632ff
#20 0.359 yarn install v1.22.19
#20 0.518 [1/5] Validating package.json...
#20 0.534 [2/5] Resolving packages...
#20 1.017 [3/5] Fetching packages...
#20 40.96 [4/5] Linking dependencies...
#20 54.13 [5/5] Building fresh packages...
#20 54.73 error /app/node_modules/turbo: Command failed.
#20 54.73 Exit code: 1
#20 54.73 Command: node install.js
#20 54.73 Arguments: 
#20 54.73 Directory: /app/node_modules/turbo
#20 54.73 Output:
#20 54.73 node:internal/errors:857
#20 54.73   const err = new Error(message);
#20 54.73               ^
#20 54.73 
#20 54.73 Error: Command failed: node /app/node_modules/turbo/bin/turbo --version
#20 54.73 /app/node_modules/turbo/bin/turbo:13
#20 54.73     throw e;
#20 54.73     ^
#20 54.73 
#20 54.73 <ref *1> Error: spawnSync /app/node_modules/turbo-linux-64/bin/turbo ENOENT
#20 54.73     at Object.spawnSync (node:internal/child_process:1119:20)
#20 54.73     at spawnSync (node:child_process:847:24)
#20 54.73     at Object.execFileSync (node:child_process:890:15)
#20 54.73     at Object.<anonymous> (/app/node_modules/turbo/bin/turbo:6:28)
#20 54.73     at Module._compile (node:internal/modules/cjs/loader:1155:14)
#20 54.73     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
#20 54.73     at Module.load (node:internal/modules/cjs/loader:1033:32)
#20 54.73     at Function.Module._load (node:internal/modules/cjs/loader:868:12)
#20 54.73     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
#20 54.73     at node:internal/main/run_main_module:22:47 {
#20 54.73   errno: -2,
#20 54.73   code: 'ENOENT',
#20 54.73   syscall: 'spawnSync /app/node_modules/turbo-linux-64/bin/turbo',
#20 54.73   path: '/app/node_modules/turbo-linux-64/bin/turbo',
#20 54.73   spawnargs: [ '--version' ],
#20 54.73   error: [Circular *1],
#20 54.73   status: null,
#20 54.73   signal: null,
#20 54.73   output: null,
#20 54.73   pid: 60,
#20 54.73   stdout: null,
#20 54.73   stderr: null
#20 54.73 }
#20 54.73 
#20 54.73     at checkExecSyncError (node:child_process:861:11)
#20 54.73     at Object.execFileSync (node:child_process:896:15)
#20 54.73     at validateBinaryVersion (/app/node_modules/turbo/install.js:25:6)
#20 54.73     at /app/node_modules/turbo/install.js:305:5 {
#20 54.73   status: 1,
#20 54.73   signal: null,
#20 54.73   output: [
#20 54.73     null,
#20 54.73     Buffer(0) [Uint8Array] [],
#20 54.73     Buffer(1079) [Uint8Array] [
#20 54.73        47,  97, 112, 112,  47, 110, 111, 100, 101,  95, 109, 111,
#20 54.73       100, 117, 108, 101, 115,  47, 116, 117, 114,  98, 111,  47,
#20 54.73        98, 105, 110,  47, 116, 117, 114,  98, 111,  58,  49,  51,
#20 54.73        10,  32,  32,  32,  32, 116, 104, 114, 111, 119,  32, 101,
#20 54.73        59,  10,  32,  32,  32,  32,  94,  10,  10,  60, 114, 101,
#20 54.73       102,  32,  42,  49,  62,  32,  69, 114, 114, 111, 114,  58,
#20 54.73        32, 115, 112,  97, 119, 110,  83, 121, 110,  99,  32,  47,
#20 54.73        97, 112, 112,  47, 110, 111, 100, 101,  95, 109, 111, 100,
#20 54.73       117, 108, 101, 115,
#20 54.73       ... 979 more items
#20 54.73     ]
#20 54.73   ],
#20 54.73   pid: 50,
#20 54.73   stdout: Buffer(0) [Uint8Array] [],
#20 54.73   stderr: Buffer(1079) [Uint8Array] [
#20 54.73      47,  97, 112, 112,  47, 110, 111, 100, 101,  95, 109, 111,
#20 54.73     100, 117, 108, 101, 115,  47, 116, 117, 114,  98, 111,  47,
#20 54.73      98, 105, 110,  47, 116, 117, 114,  98, 111,  58,  49,  51,
#20 54.73      10,  32,  32,  32,  32, 116, 104, 114, 111, 119,  32, 101,
#20 54.73      59,  10,  32,  32,  32,  32,  94,  10,  10,  60, 114, 101,
#20 54.73     102,  32,  42,  49,  62,  32,  69, 114, 114, 111, 114,  58,
#20 54.73      32, 115, 112,  97, 119, 110,  83, 121, 110,  99,  32,  47,
#20 54.73      97, 112, 112,  47, 110, 111, 100, 101,  95, 109, 111, 100,
#20 54.73     117, 108, 101, 115,
#20 54.73     ... 979 more items
#20 54.73   ]
#20 54.73 }
#20 54.73 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
#20 ERROR: executor failed running [/bin/sh -c yarn install]: exit code: 1
------
 > [installer  7/11] RUN yarn install:
------
executor failed running [/bin/sh -c yarn install]: exit code: 1
```

I believe the issue is that [`turbo` is a `devDependency`](https://github.com/vercel/turborepo/blob/d79261f1b6da79ee5cbeb3f0988003a303eb15e3/examples/with-docker/package.json#L21) so running `yarn install` in the `installer` target will fail.

If I also add `libc6-compat` to the `installer` target the build works:

```
#10 [installer  3/12] RUN apk add --no-cache libc6-compat
#10 sha256:b243f37f6b65b4d14ec41f7f8cf3e09d9eedc1b9b3c0d5e75b884a74001cfbb1
#10 0.234 fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/main/x86_64/APKINDEX.tar.gz
#10 0.425 fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/community/x86_64/APKINDEX.tar.gz
#10 0.674 (1/1) Installing libc6-compat (1.2.3-r0)
#10 0.697 OK: 8 MiB in 17 packages
#10 DONE 0.7s
```
...

```
#19 [installer  8/12] RUN yarn install
#19 sha256:1b9f52662924cd3d688ed4d666d814152da2db8c2978fb983605229257dd74a0
#19 0.357 yarn install v1.22.19
#19 0.495 [1/5] Validating package.json...
#19 0.514 [2/5] Resolving packages...
#19 1.045 [3/5] Fetching packages...
#19 42.79 [4/5] Linking dependencies...
#19 54.85 [5/5] Building fresh packages...
#19 57.89 Done in 57.54s.
#19 DONE 59.3s

#20 [installer  9/12] COPY --from=builder /app/out/full/ .
```

To avoid copy and pasting of this any other base image requirements in the future, I'd recommend adding a target like the following to base the other targets upon which may also warrant a comment by the `runner` in case the runtime environment also depends on `libc6-compat` or other additional Alpine packages: 

```
FROM node:alpine AS base
RUN apk add --no-cache libc6-compat
RUN apk update

FROM base AS builder
#...
FROM base AS installer
# ...
```

### Expected Behavior

Docker build builds.

### To Reproduce

Cannot share private repo, but the `with-docker` example should be sufficient, but cannot test it there due to #2284.

**Comment by 31i0t** [comment]
Can confirm I get the same issue on a clean clone of the `with-docker` example. The suggested fix of adding a target based on another target works as well.

**Comment by laat** [comment]
Apply this patch

```patch
 # Add lockfile and package.json's of isolated subworkspace
 FROM node:alpine AS installer
+RUN apk add --no-cache libc6-compat
 RUN apk update
 WORKDIR /app
```

**Comment by sharpsteelsoftware** [comment]
Fresh checkout of with-docker fails with 

```
------
 > [deps 1/4] RUN apk add --no-cache libc6-compat:
0.119 fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/main/aarch64/APKINDEX.tar.gz
0.271 6000078AFFFF0000:error:0A000086:SSL routines:tls_post_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1889:
0.271 fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/community/aarch64/APKINDEX.tar.gz
0.271 WARNING: fetching https://dl-cdn.alpinelinux.org/alpine/v3.18/main: Permission denied
0.384 6000078AFFFF0000:error:0A000086:SSL routines:tls_post_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1889:
0.385 WARNING: fetching https://dl-cdn.alpinelinux.org/alpine/v3.18/community: Permission denied
0.385 ERROR: unable to select packages:
0.385   libc6-compat (no such package):
0.385     required by: world[libc6-compat]
------
Dockerfile:6
--------------------
   4 |     FROM base AS deps
   5 |     # Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
   6 | >>> RUN apk add --no-cache libc6-compat
   7 |     WORKDIR /app
   8 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c apk add --no-cache libc6-compat" did not complete successfully: exit code: 1
```

**Comment by anhtpde140084** [comment]
@sharpsteelsoftware Did you solve it? I have the same problem as you :(

**Comment by sharpsteelsoftware** [comment]
Here is my dockerfile  @anhtpde140084 

FROM node:18-alpine

WORKDIR /app

# ZScaler config
RUN yarn config set strict-ssl false

# Install dependencies based on the preferred package manager
COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
RUN \
  if [ -f yarn.lock ]; then NODE_TLS_REJECT_UNAUTHORIZED=0 yarn --frozen-lockfile; \
  elif [ -f package-lock.json ]; then npm ci; \
  elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i; \
  # Allow install without lockfile, so example works even without Node.js installed locally
  else echo "Warning: Lockfile not found. It is recommended to commit lockfiles to version control." && yarn install; \
  fi

COPY app ./app
COPY common ./common
COPY config ./config
COPY lib ./lib
COPY prisma ./prisma
COPY public ./public
COPY theme ./theme
COPY util ./util

COPY .env.development.local . 
COPY next.config.js .
COPY postcss.config.js .
COPY tsconfig.json .
COPY tailwind.config.js .

# Next.js collects completely anonymous telemetry data about general usage. Learn more here: https://nextjs.org/telemetry
# Uncomment the following line to disable telemetry at run time
ENV NEXT_TELEMETRY_DISABLED 1

# Note: Don't expose ports here, Compose will handle that for us

RUN NODE_TLS_REJECT_UNAUTHORIZED=0 npx prisma generate

# Start Next.js in development mode based on the preferred package manager
ENV HOSTNAME 0.0.0.0
CMD \
  if [ -f yarn.lock ]; then NODE_TLS_REJECT_UNAUTHORIZED=0 yarn dev; \
  elif [ -f package-lock.json ]; then npm run dev; \
  elif [ -f pnpm-lock.yaml ]; then pnpm dev; \
  else yarn dev; \
  fi

**Comment by michaelmagero** [comment]
If you are experiencing this on Mac instead of libc6-compat try renaming it to libc6-dev and make sure you are using apt-get install

**Comment by anthonyshew** [comment]
Closing for inactivity!
