### ISSUE TITLE
[Turbopack] dev server fails in Next.js/chakra-ui/framer motion project

### ISSUE THREAD

**Issue by peterjuras** [vercel/turbo#2449]
### What version of Turbopack are you using?

The one that ships with Next.js 13

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Linux

### Describe the Bug

When running `next dev --turbo` and accessing the root page (`localhost:3000`), the following error is thrown and no page is visible:

```
error - [rendering] [root of the dev server]/
  Error during SSR Rendering
  ReferenceError: scrapeMotionValuesFromProps is not defined
    at <unknown> (.next/server/pages/chunks/node_modules_f6b081.js:7:8)
    at [project-with-next]/node_modules/framer-motion/dist/es/render/html/config-motion.mjs (ecmascript) (.next/server/pages/chunks/node_modules_f6b081.js:6666:3)
    at <unknown> (.next/server/pages/chunks/_1fb706.js:4128:21)
    at runModuleExecutionHooks (.next/server/pages/chunks/_1fb706.js:4166:5)
    at instantiateModule (.next/server/pages/chunks/_1fb706.js:4127:5)
    at getOrInstantiateModuleFromParent (.next/server/pages/chunks/_1fb706.js:4208:12)
    at esmImport (.next/server/pages/chunks/_1fb706.js:3937:20)
    at <unknown> (.next/server/pages/chunks/node_modules_f6b081.js:1:0)
    at [project-with-next]/node_modules/framer-motion/dist/es/render/dom/utils/create-config.mjs (ecmascript) (.next/server/pages/chunks/node_modules_f6b081.js:4927:3)
    at <unknown> (.next/server/pages/chunks/_1fb706.js:4128:21)
    at runModuleExecutionHooks (.next/server/pages/chunks/_1fb706.js:4166:5)
    at instantiateModule (.next/server/pages/chunks/_1fb706.js:4127:5)
    at getOrInstantiateModuleFromParent (.next/server/pages/chunks/_1fb706.js:4208:12)
    at esmImport (.next/server/pages/chunks/_1fb706.js:3937:20)
    at <unknown> (.next/server/pages/chunks/node_modules_f6b081.js:1:0)
    at [project-with-next]/node_modules/framer-motion/dist/es/render/dom/motion.mjs (ecmascript) (.next/server/pages/chunks/node_modules_f6b081.js:2137:3)
    at <unknown> (.next/server/pages/chunks/_1fb706.js:4128:21)
    at runModuleExecutionHooks (.next/server/pages/chunks/_1fb706.js:4166:5)
    at instantiateModule (.next/server/pages/chunks/_1fb706.js:4127:5)
    at getOrInstantiateModuleFromParent (.next/server/pages/chunks/_1fb706.js:4208:12)
    at esmImport (.next/server/pages/chunks/_1fb706.js:3937:20)
    at <unknown> (.next/server/pages/chunks/node_modules_f6b081.js:1:0)
    at [project-with-next]/node_modules/framer-motion/dist/es/index.mjs (ecmascript) (.next/server/pages/chunks/node_modules_f6b081.js:2097:3)
    at <unknown> (.next/server/pages/chunks/_1fb706.js:4128:21)
    at runModuleExecutionHooks (.next/server/pages/chunks/_1fb706.js:4166:5)
    at instantiateModule (.next/server/pages/chunks/_1fb706.js:4127:5)
    at getOrInstantiateModuleFromParent (.next/server/pages/chunks/_1fb706.js:4208:12)
    at esmImport (.next/server/pages/chunks/_1fb706.js:3937:20)
    at <unknown> (.next/server/pages/chunks/node_modules_f6b081.js:2:0)
    at [project-with-next]/node_modules/@chakra-ui/transition/dist/index.esm.js (ecmascript) (.next/server/pages/chunks/node_modules_f6b081.js:1877:3)
    at <unknown> (.next/server/pages/chunks/_1fb706.js:4128:21)
    at runModuleExecutionHooks (.next/server/pages/chunks/_1fb706.js:4166:5)
    at instantiateModule (.next/server/pages/chunks/_1fb706.js:4127:5)
    at getOrInstantiateModuleFromParent (.next/server/pages/chunks/_1fb706.js:4208:12)
    at esmImport (.next/server/pages/chunks/_1fb706.js:3937:20)
    at <unknown> (.next/server/pages/chunks/_cb97a5.js:2:0)
    at [project-with-next]/node_modules/@chakra-ui/accordion/dist/index.esm.js (ecmascript) (.next/server/pages/chunks/_cb97a5.js:1604:3)
    at <unknown> (.next/server/pages/chunks/_1fb706.js:4128:21)
    at runModuleExecutionHooks (.next/server/pages/chunks/_1fb706.js:4166:5)
    at instantiateModule (.next/server/pages/chunks/_1fb706.js:4127:5)
    at getOrInstantiateModuleFromParent (.next/server/pages/chunks/_1fb706.js:4208:12)
    at esmImport (.next/server/pages/chunks/_1fb706.js:3937:20)
    at <unknown> (.next/server/pages/chunks/_1fb706.js:2:0)
    at [project-with-next]/node_modules/@chakra-ui/react/dist/index.esm.js (ecmascript) (.next/server/pages/chunks/_1fb706.js:3051:3)
    at <unknown> (.next/server/pages/chunks/_1fb706.js:4128:21)
    at runModuleExecutionHooks (.next/server/pages/chunks/_1fb706.js:4166:5)
    at instantiateModule (.next/server/pages/chunks/_1fb706.js:4127:5)
    at getOrInstantiateModuleFromParent (.next/server/pages/chunks/_1fb706.js:4208:12)
    at esmImport (.next/server/pages/chunks/_1fb706.js:3937:20)
    at <unknown> (.next/server/pages/chunks/_1fb706.js:1:0)
    at [project-with-next]/pages/_app.tsx (ecmascript) (.next/server/pages/chunks/_1fb706.js:318:3)
    at <unknown> (.next/server/pages/chunks/_1fb706.js:4128:21)
    at runModuleExecutionHooks (.next/server/pages/chunks/_1fb706.js:4166:5)
    at instantiateModule (.next/server/pages/chunks/_1fb706.js:4127:5)
    at getOrInstantiateModuleFromParent (.next/server/pages/chunks/_1fb706.js:4208:12)
    at esmImport (.next/server/pages/chunks/_1fb706.js:3937:20)
    at <unknown> (.next/server/pages/chunks/_1fb706.js:1:0)
    at [project-with-next]/pages/index.tsx/server-renderer.tsx (ecmascript) (.next/server/pages/chunks/_1fb706.js:265:3)
    at <unknown> (.next/server/pages/chunks/_1fb706.js:4128:21)
    at runModuleExecutionHooks (.next/server/pages/chunks/_1fb706.js:4166:5)
    at instantiateModule (.next/server/pages/chunks/_1fb706.js:4127:5)
    at instantiateRuntimeModule (.next/server/pages/chunks/_1fb706.js:4712:12)
    at <unknown> (.next/server/pages/chunks/_1fb706.js:3767:1)
    at <unknown> (.next/server/pages/chunks/_1fb706.js:4763:39)
    at <anonymous>
    at Object.registerChunk [as push] (.next/server/pages/chunks/_1fb706.js:4763:25)
    at Object.<anonymous> (.next/server/pages/chunks/_cb97a5.js:1:41)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (.next/server/pages/index.js:12:1)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at <unknown> (node:internal/main/run_main_module:23:47)
```

### Expected Behavior

There should be no error and the page should render correctly, as it does with `next dev`.

### To Reproduce

You can clone and run `yarn dev` in the reproduction repo below, it is using a barebones `yarn create next-app` project with the minimal steps to install chakra ui from [its docs](https://chakra-ui.com/getting-started/nextjs-guide).

Steps with reproduction repo:
* `git clone https://github.com/peterjuras/repro-chakra-ui-turbo-test.git`
* `yarn` # yarn v1
* `yarn dev`
* Open `localhost:3000` in a browser

-> Observe error

### Reproduction Repo

https://github.com/peterjuras/repro-chakra-ui-turbo-test

**Comment by padmaia** [comment]
Not seeing this issue on Next.js 13.2.4
