### ISSUE TITLE
[turborepo] `prune` panics with error `Unable to find primary descriptor`

### ISSUE THREAD

**Issue by runeh** [vercel/turbo#3273]
### What version of Turborepo are you using?

1.7.0

### What package manager are you using / does the bug impact?

Yarn v2/v3 (node_modules linker only)

### What operating system are you using?

Mac

### Describe the Bug

When running `yarn turbo prune --scope=<my app>`, turbo panics. Probably the same as #2146.

```
panic: Unable to find primary descriptor @google-cloud/datastore@npm:google-cloud/datastore@npm:^7.0.0

goroutine 21 [running]:
github.com/vercel/turbo/cli/internal/lockfile.(*BerryLockfile).Subgraph(0x140005aa140, {0x1400093e200, 0x1d, 0x140003d8000?}, {0x1400112a000, 0x1e14, 0x100f5eec4?})
	github.com/vercel/turbo/cli/internal/lockfile/berry_lockfile.go:195 +0xde0
github.com/vercel/turbo/cli/internal/prune.(*prune).prune(0x140011c5ef0, 0x140002596b0)
	github.com/vercel/turbo/cli/internal/prune/prune.go:167 +0xc08
github.com/vercel/turbo/cli/internal/prune.ExecutePrune(0x0?, 0x140001da380)
	github.com/vercel/turbo/cli/internal/prune/prune.go:41 +0xec
github.com/vercel/turbo/cli/internal/cmd.RunWithArgs.func1()
	github.com/vercel/turbo/cli/internal/cmd/root.go:80 +0x160
created by github.com/vercel/turbo/cli/internal/cmd.RunWithArgs
	github.com/vercel/turbo/cli/internal/cmd/root.go:67 +0x354
```

It fails on other dependencies as well. I'm guessing there's some processing in parallel, so which one fails is somewhat random.

All the he failing dependencies have yarn patches applied. The resolution lines in package.json for dependencies I've seen fail look like this:

```
"@types/extract-files": "patch:@types/extract-files@*#./.yarn/patches/@types+extract-files.patch",
"@google-cloud/datastore": "patch:@google-cloud/datastore@npm:^7.0.0#./.yarn/patches/@google-cloud-datastore-npm-7.0.0-9
94584c630.patch"
"@sentry/browser": "patch:@sentry/browser@npm:7.20.1#./.yarn/patches/@sentry-browser-npm-7.20.1-2ad3078ff7.patch"
```

### Expected Behavior

It prunes.

### To Reproduce

I'm not able to share the repo, as it's company internal. I've not been able to reduce it to a minimal test case unfortunately. I might be able to share the lockfile, or parts of it if that helps.

**Comment by chris-olszewski** [comment]
Hi @runeh, if your project is using `resolution` in the root `package.json`, then this will probably be resolved once I get a fix for #2791. Leaving open in case it differs.

**Comment by runeh** [comment]
@chris-olszewski I tested canary 1.9.4-canary.6 in my repo. Getting a new kind of crash:

```
thread '<unnamed>' panicked at 'No locator found for @opentelemetry/instrumentation-http@patch:@opentelemetry/instrumentation-http@npm:^0.38.0#../../.yarn/patches/@opentelemetry-instrumentation-http-npm-0.38.0-664726f09a.patch', crates/turborepo-lockfiles/src/berry/mod.rs:265:44
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
SIGABRT: abort
PC=0x19be94724 m=8 sigcode=0
signal arrived during cgo execution

goroutine 51 [syscall]:
runtime.cgocall(0x1053eff4c, 0x140000d9588)
	runtime/cgocall.go:157 +0x54 fp=0x140000d9540 sp=0x140000d9500 pc=0x104e16684
github.com/vercel/turbo/cli/internal/ffi._Cfunc_subgraph({0x161f90, 0x158098000})
	_cgo_gotypes.go:152 +0x40 fp=0x140000d9580 sp=0x140000d9540 pc=0x10529c230
github.com/vercel/turbo/cli/internal/ffi.Subgraph({0x10579f670, 0x5}, {0x14000800000, 0x1339b7, 0x1339b8}, {0x14000230600, 0x20, 0x20}, {0x140006de000, 0x1c27, ...}, ...)
	github.com/vercel/turbo/cli/internal/ffi/ffi.go:238 +0x1e4 fp=0x140000d9690 sp=0x140000d9580 pc=0x10529d604
github.com/vercel/turbo/cli/internal/lockfile.(*BerryLockfile).Subgraph(0x140001bbf20, {0x14000230400, 0x20, 0x14000032020?}, {0x140006de000, 0x1c27, 0x2200})
	github.com/vercel/turbo/cli/internal/lockfile/berry_lockfile.go:40 +0x94 fp=0x140000d9720 sp=0x140000d9690 pc=0x1052ac114
github.com/vercel/turbo/cli/internal/prune.(*prune).prune(0x140000d9f50, 0x140002f2e40)
	github.com/vercel/turbo/cli/internal/prune/prune.go:175 +0xc78 fp=0x140000d9ef0 sp=0x140000d9720 pc=0x1053ca6a8
github.com/vercel/turbo/cli/internal/prune.ExecutePrune(0x0?, 0x14000293d40)
	github.com/vercel/turbo/cli/internal/prune/prune.go:44 +0xe0 fp=0x140000d9f60 sp=0x140000d9ef0 pc=0x1053c9770
github.com/vercel/turbo/cli/internal/cmd.RunWithExecutionState.func1()
	github.com/vercel/turbo/cli/internal/cmd/root.go:70 +0x114 fp=0x140000d9fd0 sp=0x140000d9f60 pc=0x1053ef2d4
runtime.goexit()
	runtime/asm_arm64.s:1270 +0x4 fp=0x140000d9fd0 sp=0x140000d9fd0 pc=0x104e7a684
created by github.com/vercel/turbo/cli/internal/cmd.RunWithExecutionState
	github.com/vercel/turbo/cli/internal/cmd/root.go:65 +0x2c0

goroutine 1 [select]:
github.com/vercel/turbo/cli/internal/cmd.RunWithExecutionState(0x14000293d40, {0x1057a776a, 0xe})
	github.com/vercel/turbo/cli/internal/cmd/root.go:82 +0x2f8
main.main()
	github.com/vercel/turbo/cli/cmd/turbo/main.go:26 +0x148

goroutine 34 [syscall]:
os/signal.signal_recv()
	runtime/sigqueue.go:148 +0x30
os/signal.loop()
	os/signal/signal_unix.go:23 +0x20
created by os/signal.Notify.func1.1
	os/signal/signal.go:151 +0x30

goroutine 50 [chan receive]:
github.com/vercel/turbo/cli/internal/signals.NewWatcher.func1()
	github.com/vercel/turbo/cli/internal/signals/signals.go:56 +0x30
created by github.com/vercel/turbo/cli/internal/signals.NewWatcher
	github.com/vercel/turbo/cli/internal/signals/signals.go:55 +0x138

r0      0x0
r1      0x0
r2      0x0
r3      0x0
r4      0x0
r5      0x1
r6      0x6261745f74706563
r7      0x1d0
r8      0x8f83d517a5c9a943
r9      0x8f83d516cef25943
r10     0x110000
r11     0x26
r12     0x1053efc00
r13     0x104e13910
r14     0x0
r15     0x94
r16     0x148
r17     0x1fbe54f20
r18     0x0
r19     0x6
r20     0x16b3bf000
r21     0xd03
r22     0x16b3bf0e0
r23     0x1059216d8
r24     0x1
r25     0x6
r26     0x139156950
r27     0x16b3be8e0
r28     0x140003821a0
r29     0x16b3be1b0
lr      0x19becbc28
sp      0x16b3be190
pc      0x19be94724
fault   0x19be94724```

**Comment by runeh** [comment]
canary .7:
 ```
thread '<unnamed>' panicked at 'No locator found for @opentelemetry/instrumentation-http@patch:@opentelemetry/instrumentation-http@npm:^0.38.0#../../.yarn/patches/@opentelemetry-instrumentation-http-npm-0.38.0-664726f09a.patch', crates/turborepo-lockfiles/src/berry/mod.rs:265:44
stack backtrace:
   0:        0x105184b60 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h6cecb049291c8336
   1:        0x1051cee0c - core::fmt::write::hfbe3d7f51079d41f
   2:        0x10517a8d8 - std::io::Write::write_fmt::h14bea80b5c21e88e
   3:        0x105184974 - std::sys_common::backtrace::print::h83bb5cd649f18495
   4:        0x1051873fc - std::panicking::default_hook::{{closure}}::h4dbb5836875914e6
   5:        0x105187154 - std::panicking::default_hook::hb36c93446818c483
   6:        0x1051879b8 - std::panicking::rust_panic_with_hook::hc140496f44bf613c
   7:        0x1051878ec - std::panicking::begin_panic_handler::{{closure}}::hf62c66af6c443681
   8:        0x105184f80 - std::sys_common::backtrace::__rust_end_short_backtrace::h37ac24b5f616b645
   9:        0x105187648 - _rust_begin_unwind
  10:        0x1052013d4 - core::panicking::panic_fmt::hc6e9d0b6c5d1e4a1
  11:        0x105047d20 - <turborepo_lockfiles[88fb6b0be5b28043]::berry::BerryLockfile>::subgraph
  12:        0x1050496e4 - turborepo_lockfiles[88fb6b0be5b28043]::berry::berry_subgraph
  13:        0x104ee67f4 - _subgraph
  14:        0x104e32a0c - __cgo_49699e29077a_Cfunc_subgraph
fatal runtime error: failed to initiate panic, error 5
SIGABRT: abort
PC=0x186b60724 m=8 sigcode=0
signal arrived during cgo execution

goroutine 36 [syscall]:
runtime.cgocall(0x104e329e8, 0x14000169548)
	runtime/cgocall.go:157 +0x54 fp=0x14000169500 sp=0x140001694c0 pc=0x104858c84
github.com/vercel/turbo/cli/internal/ffi._Cfunc_subgraph({0x161f90, 0x150018000})
	_cgo_gotypes.go:165 +0x40 fp=0x14000169540 sp=0x14000169500 pc=0x104cdef00
github.com/vercel/turbo/cli/internal/ffi.Subgraph({0x105203f90, 0x5}, {0x14000700000, 0x1339b7, 0x1339b8}, {0x140004f8000, 0x20, 0x20}, {0x14000c4e000, 0x1c27, ...}, ...)
	github.com/vercel/turbo/cli/internal/ffi/ffi.go:238 +0x1e4 fp=0x14000169650 sp=0x14000169540 pc=0x104ce02d4
github.com/vercel/turbo/cli/internal/lockfile.(*BerryLockfile).Subgraph(0x140005af7e0, {0x140001b0400, 0x20, 0x14000032100?}, {0x14000c4e000, 0x1c27, 0x2200})
	github.com/vercel/turbo/cli/internal/lockfile/berry_lockfile.go:40 +0x94 fp=0x140001696e0 sp=0x14000169650 pc=0x104ceeff4
github.com/vercel/turbo/cli/internal/prune.(*prune).prune(0x14000169f50, 0x1400027ee40)
	github.com/vercel/turbo/cli/internal/prune/prune.go:175 +0xc78 fp=0x14000169ef0 sp=0x140001696e0 pc=0x104e0cd38
github.com/vercel/turbo/cli/internal/prune.ExecutePrune(0x0?, 0x1400028a120)
	github.com/vercel/turbo/cli/internal/prune/prune.go:44 +0xe0 fp=0x14000169f60 sp=0x14000169ef0 pc=0x104e0be00
github.com/vercel/turbo/cli/internal/cmd.RunWithExecutionState.func1()
	github.com/vercel/turbo/cli/internal/cmd/root.go:70 +0x114 fp=0x14000169fd0 sp=0x14000169f60 pc=0x104e31c94
runtime.goexit()
	runtime/asm_arm64.s:1270 +0x4 fp=0x14000169fd0 sp=0x14000169fd0 pc=0x1048bcc84
created by github.com/vercel/turbo/cli/internal/cmd.RunWithExecutionState
	github.com/vercel/turbo/cli/internal/cmd/root.go:65 +0x2c0

goroutine 1 [select]:
github.com/vercel/turbo/cli/internal/cmd.RunWithExecutionState(0x1400028a120, {0x10520c08a, 0xe})
	github.com/vercel/turbo/cli/internal/cmd/root.go:82 +0x2f8
main.main()
	github.com/vercel/turbo/cli/cmd/turbo/main.go:30 +0x1d8

goroutine 34 [syscall]:
os/signal.signal_recv()
	runtime/sigqueue.go:148 +0x30
os/signal.loop()
	os/signal/signal_unix.go:23 +0x20
created by os/signal.Notify.func1.1
	os/signal/signal.go:151 +0x30

goroutine 35 [chan receive]:
github.com/vercel/turbo/cli/internal/signals.NewWatcher.func1()
	github.com/vercel/turbo/cli/internal/signals/signals.go:56 +0x30
created by github.com/vercel/turbo/cli/internal/signals.NewWatcher
	github.com/vercel/turbo/cli/internal/signals/signals.go:55 +0x138

r0      0x0
r1      0x0
r2      0x0
r3      0x0
r4      0x0
r5      0x1
r6      0x6261745f74706563
r7      0x1d0
r8      0x2b09da8069b68146
r9      0x2b09da8102213146
r10     0x110000
r11     0x26
r12     0x104e32650
r13     0x104855f10
r14     0x0
r15     0x2e8
r16     0x148
r17     0x1e6b2cf20
r18     0x0
r19     0x6
r20     0x16b97b000
r21     0x1903
r22     0x16b97b0e0
r23     0x105388228
r24     0x1
r25     0x600001b8e124
r26     0xa
r27     0x16b97a8e0
r28     0xe
r29     0x16b97a1d0
lr      0x186b97c28
sp      0x16b97a1b0
pc      0x186b60724
fault   0x186b60724
```

**Comment by runeh** [comment]
Tested 1.9.4, still crashes.

**Comment by runeh** [comment]
Still crashing in 1.10.3

**Comment by runeh** [comment]
Crashing in 1.10.6

**Comment by runeh** [comment]
Bug seems to have moved to rust in 1.10.16 :)

```
thread 'main' panicked at crates/turborepo-lockfiles/src/berry/mod.rs:456:44:
No locator found for unleash-client@patch:unleash-client@npm:^4.0.0#../../.yarn/patches/unleash-client-npm-4.0.0-9ad93d49c3.patch
stack backtrace:
   0:        0x100a297a0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h860c7bdc0ac64ed5
   1:        0x100726400 - core::fmt::write::h7e6650b8aa1762db
   2:        0x1009fef1c - std::io::Write::write_fmt::h61782b5a5e1d9926
   3:        0x100a2b750 - std::sys_common::backtrace::print::hb0bcea9c33afc3d5
   4:        0x100a2b3b4 - std::panicking::default_hook::{{closure}}::ha1e0891a01818dc6
   5:        0x100a2c3f4 - std::panicking::rust_panic_with_hook::h0a0e0d9333300324
   6:        0x100a2bebc - std::panicking::begin_panic_handler::{{closure}}::hccb699a50bf03f15
   7:        0x100a2be28 - std::sys_common::backtrace::__rust_end_short_backtrace::hbe878a6902d38f1b
   8:        0x100a2be1c - _rust_begin_unwind
   9:        0x101087508 - core::panicking::panic_fmt::hf6ce74cb9aa95247
  10:        0x100ef11e4 - <turborepo_lockfiles[f05b019e08ea56e]::berry::BerryLockfile as turborepo_lockfiles[f05b019e08ea56e]::Lockfile>::subgraph
  11:        0x100dc8de0 - turborepo_lib[5506982201d88974]::commands::prune::prune
  12:        0x100c63e64 - turborepo_lib[5506982201d88974]::cli::run::{closure#0}.33398
  13:        0x100c5ecbc - <tokio[7d1ff1431fb4a416]::runtime::park::CachedParkThread>::block_on::<turborepo_lib[5506982201d88974]::cli::run::{closure#0}>
  14:        0x100e02384 - turborepo_lib[5506982201d88974]::cli::run
  15:        0x100da77a8 - turborepo_lib[5506982201d88974]::shim::run_correct_turbo
  16:        0x100da462c - turborepo_lib[5506982201d88974]::main
  17:        0x100b25218 - turbo[d66cc355fa45ca13]::main
  18:        0x100b3511c - std[611a655d33f2eb9]::sys_common::backtrace::__rust_begin_short_backtrace::<fn() -> core[c944d04e15ab2514]::result::Result<(), anyhow[c883198c32ba45c1]::Error>, core[c944d04e15ab2514]::result::Result<(), anyhow[c883198c32ba45c1]::Error>>
  19:        0x100b24d14 - _main
```
