### ISSUE TITLE
[turborepo] Install in FreeBSD

### ISSUE THREAD

**Issue by ismatim** [vercel/turbo#3394]
### What version of Turborepo are you using?

1.7.0

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Other

### Describe the Bug

On **1.2.8** it was working totally fine: Now, I have this issue.

```
npm ERR! path /tank_data_1/clients/app/node_modules/turbo
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! /tank_data_1/clients/app/node_modules/turbo/node-platform.js:38
npm ERR!     throw new Error(`Unsupported platform: ${platformKey}`);
npm ERR!           ^
npm ERR!
npm ERR! Error: Unsupported platform: freebsd x64 LE
npm ERR!     at pkgAndSubpathForCurrentPlatform (/tank_data_1/clients/app/node_modules/turbo/node-platform.js:38:11)
npm ERR!     at checkAndPreparePackage (/tank_data_1/clients/app/node_modules/turbo/install.js:260:28)
npm ERR!     at Object.<anonymous> (/tank_data_1/clients/app/node_modules/turbo/install.js:310:1)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1165:14)
npm ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:1043:32)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:878:12)
npm ERR!     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
npm ERR!     at node:internal/main/run_main_module:22:47

``` 

### Expected Behavior

A correct installation.

### To Reproduce

npm i turbo@latest

**Comment by aloxlamm** [comment]
same on platform (unix like):
linux s390x BE

# turbo/node-platform.js  L19:

`const knownUnixlikePackages = {
  "darwin arm64 LE": "turbo-darwin-arm64",
  "darwin x64 LE": "turbo-darwin-64",
  "linux arm64 LE": "turbo-linux-arm64",
  "linux x64 LE": "turbo-linux-64",
};`

**Comment by anthonyshew** [comment]
Closing in favor of discussions on #7083.
