### ISSUE TITLE
[turbopack] Unable to resolve local fonts with relative url in the css file

### ISSUE THREAD

**Issue by navin-moorthy** [vercel/turbo#3426]
### What version of Turbopack are you using?

1.0.0

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

Local fonts that are defined like below in css are not resolved,

```
@font-face {
  font-family: InterVar;
  font-weight: 100 900;
  font-display: swap;
  font-style: normal;
  font-named-instance: "Regular";
  src: url("/fonts/Inter.var-english.woff2") format("woff2");
}
```

<details>
<summary>Error logs</summary>

```
TURBOPACK (alpha)

Thank you for trying Next.js v13 with Turbopack! As a reminder,
Turbopack is currently in alpha and not yet ready for production.
We appreciate your ongoing support as we work to make it ready
for everyone.

Learn more about Next.js v13 and Turbopack: https://nextjs.link/with-turbopack
Please direct feedback to: https://nextjs.link/turbopack-feedback

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
event - initial compilation 46ms
error - [resolve]
  ... [6 paths] are hidden, run with --show-all to show them
warning - [parse]
  ... [9 paths] are hidden, run with --show-all to show them
error - [resolve]
  src/styles
    Error resolving server relative import: not implemented yet
    unable to resolve server relative "/fonts/Inter.var-english.woff2"

    Error resolving server relative import: not implemented yet
    unable to resolve server relative "/fonts/Inter.var-extended-b.woff2"

    Error resolving server relative import: not implemented yet
    unable to resolve server relative "/fonts/Inter.var-latin-extended-a.woff2"

    ... [4 more issues] are hidden, run with --show-all to show all
  src/styles/global.css
    Error resolving url request
    unable to resolve server relative "/fonts/Inter.var-english.woff2"

    Error resolving url request
    unable to resolve server relative "/fonts/Inter.var-extended-b.woff2"

    Error resolving url request
    unable to resolve server relative "/fonts/Inter.var-latin-extended-a.woff2"

    ... [4 more issues] are hidden, run with --show-all to show all
  ... [2 more paths] are hidden, run with --show-all to show all
warning - [parse]
  ... [6 paths] are hidden, run with --show-all to show them
error - [rendering] [root of the server]/
  Error during SSR Rendering
  TypeError: __TURBOPACK__imported__module__$5b$project$2d$with$2d$next$5d2f$node_modules$2f2e$pnpm$2f$chalk$40$3$2e$0$2e$0$2f$node_modules$2f$chalk$2f$source$2f$index$2e$js__.cyan is not a function
    at <unknown> (/.next/server/pages/chunks/_721785.js:17384:177)
    at Module.[project-with-next]/node_modules/.pnpm/@sentry+nextjs@7.31.1_next@13.1.4+react@18.2.0/node_modules/@sentry/nextjs/esm/server/utils/nextLogger.js (ecmascript) (/.next/server/pages/chunks/_721785.js:17404:3)
    at <unknown> (/.next/server/pages/chunks/_721785.js:90281:19)
    at runModuleExecutionHooks (/.next/server/pages/chunks/_721785.js:90321:3)
    at instantiateModule (/.next/server/pages/chunks/_721785.js:90280:3)
    at getOrInstantiateModuleFromParent (/.next/server/pages/chunks/_721785.js:90363:10)
    at esmImport (/.next/server/pages/chunks/_721785.js:90109:18)
    at <unknown> (/.next/server/pages/chunks/_721785.js:16548:264)
    at Module.[project-with-next]/node_modules/.pnpm/@sentry+nextjs@7.31.1_next@13.1.4+react@18.2.0/node_modules/@sentry/nextjs/esm/server/wrapApiHandlerWithSentry.js (ecmascript) (/.next/server/pages/chunks/_721785.js:16695:3)
    at <unknown> (/.next/server/pages/chunks/_721785.js:90281:19)
    at runModuleExecutionHooks (/.next/server/pages/chunks/_721785.js:90321:3)
    at instantiateModule (/.next/server/pages/chunks/_721785.js:90280:3)
    at getOrInstantiateModuleFromParent (/.next/server/pages/chunks/_721785.js:90363:10)
    at esmImport (/.next/server/pages/chunks/_721785.js:90109:18)
    at <unknown> (/.next/server/pages/chunks/_721785.js:15888:269)
    at Module.[project-with-next]/node_modules/.pnpm/@sentry+nextjs@7.31.1_next@13.1.4+react@18.2.0/node_modules/@sentry/nextjs/esm/server/index.js (ecmascript) (/.next/server/pages/chunks/_721785.js:16021:3)
    at <unknown> (/.next/server/pages/chunks/_721785.js:90281:19)
    at runModuleExecutionHooks (/.next/server/pages/chunks/_721785.js:90321:3)
    at instantiateModule (/.next/server/pages/chunks/_721785.js:90280:3)
    at getOrInstantiateModuleFromParent (/.next/server/pages/chunks/_721785.js:90363:10)
    at esmImport (/.next/server/pages/chunks/_721785.js:90109:18)
    at <unknown> (/.next/server/pages/chunks/_721785.js:15769:250)
    at Module.[project-with-next]/node_modules/.pnpm/@sentry+nextjs@7.31.1_next@13.1.4+react@18.2.0/node_modules/@sentry/nextjs/esm/index.server.js (ecmascript) (/.next/server/pages/chunks/_721785.js:15796:3)
    at <unknown> (/.next/server/pages/chunks/_721785.js:90281:19)
    at runModuleExecutionHooks (/.next/server/pages/chunks/_721785.js:90321:3)
    at instantiateModule (/.next/server/pages/chunks/_721785.js:90280:3)
    at getOrInstantiateModuleFromParent (/.next/server/pages/chunks/_721785.js:90363:10)
    at esmImport (/.next/server/pages/chunks/_721785.js:90109:18)
    at <unknown> (/.next/server/pages/chunks/_721785.js:1586:250)
    at Module.[project-with-next]/src/utils/captureSentryException.ts (ecmascript) (/.next/server/pages/chunks/_721785.js:1596:3)
    at <unknown> (/.next/server/pages/chunks/_721785.js:90281:19)
    at runModuleExecutionHooks (/.next/server/pages/chunks/_721785.js:90321:3)
    at instantiateModule (/.next/server/pages/chunks/_721785.js:90280:3)
    at getOrInstantiateModuleFromParent (/.next/server/pages/chunks/_721785.js:90363:10)
    at esmImport (/.next/server/pages/chunks/_721785.js:90109:18)
    at <unknown> (/.next/server/pages/chunks/_721785.js:267:118)
    at Module.[project-with-next]/src/pages/index.tsx (ecmascript) (/.next/server/pages/chunks/_721785.js:337:3)
    at <unknown> (/.next/server/pages/chunks/_721785.js:90281:19)
    at runModuleExecutionHooks (/.next/server/pages/chunks/_721785.js:90321:3)
    at instantiateModule (/.next/server/pages/chunks/_721785.js:90280:3)
    at getOrInstantiateModuleFromParent (/.next/server/pages/chunks/_721785.js:90363:10)
    at esmImport (/.next/server/pages/chunks/_721785.js:90109:18)
    at <unknown> (/.next/server/pages/chunks/_721785.js:231:102)
    at Object.[project-with-next]/src/pages/index.tsx/server-renderer.tsx (ecmascript) (/.next/server/pages/chunks/_721785.js:249:3)
    at <unknown> (/.next/server/pages/chunks/_721785.js:90281:19)
    at runModuleExecutionHooks (/.next/server/pages/chunks/_721785.js:90321:3)
    at instantiateModule (/.next/server/pages/chunks/_721785.js:90280:3)
    at instantiateRuntimeModule (/.next/server/pages/chunks/_721785.js:90885:10)
    at <unknown> (/.next/server/pages/chunks/_721785.js:89911:1)
    at <unknown> (/.next/server/pages/chunks/_721785.js:90936:37)
    at <anonymous>
    at registerChunk (/.next/server/pages/chunks/_721785.js:90936:23)
    at <anonymous>
    at <unknown> (/.next/server/pages/chunks/_721785.js:90942:22)
    at Object.<anonymous> (/.next/server/pages/chunks/_721785.js:90946:3)
    at Module._compile (node:internal/modules/cjs/loader:1165:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
    at Module.load (node:internal/modules/cjs/loader:1043:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1067:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/.next/server/pages/index.js:3:1)
    at Module._compile (node:internal/modules/cjs/loader:1165:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
    at Module.load (node:internal/modules/cjs/loader:1043:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at <unknown> (node:internal/main/run_main_module:22:47)


warning - [analyze]
  ... [3 paths] are hidden, run with --show-all to show them
event - updated in 9727ms
event - updated in 680ms
```
</details>

### Expected Behavior

Expect the turbopack to resolve it like the `next dev` does now.

### To Reproduce

Create a `global.css` & define a `@font-face` and import a local relative url like this

```
@font-face {
  font-family: InterVar;
  font-weight: 100 900;
  font-display: swap;
  font-style: normal;
  font-named-instance: "Regular";
  src: url("/fonts/Inter.var-english.woff2") format("woff2");
}
```

**Comment by theonlydaleking** [comment]
Just adding to this - it fails with relative imports in node_modules too. Which is an issue when using things like fontawesome

**Comment by ForsakenHarmony** [comment]
relative imports should be working, but the example is an absolute import (which we probably don't want to support)
