### ISSUE TITLE
[turborepo] DTS Build Success -- which happens too late

### ISSUE THREAD

**Issue by rwieruch** [vercel/turbo#3765]
### What version of Turborepo are you using?

1.2.12

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Mac

### Describe the Bug

I have two packages in my packages/ folder. Lets call them `@bigstair/form` and `@bigstair/core` whereas the former depends on the build of the latter.  If it matters, I used one of Turborepo's [examples](https://github.com/vercel/turbo/commits/main/examples/design-system) as starting point.

When I build the project, it works with a likelihood of 95%. The other 5% are caused by a `DTS Build Success` which happens too late, because the other package depends on it and is already in the middle of its build without waiting for the DTS file. 

See full log [0] whereas `@bigstair/core:dev: DTS Build success in 4575ms` is the crucial step which happens too late. 

My Turborepo configuration [1] feels already pretty restrictive to exclude caching bugs.

Any help is very much appreciated. While rerunning the build command on the command line usually works, it is a stressful situation that I created for my teammates here.

[0]

```
@bigstair/core:dev: cache bypass, force executing 981d6ed811e33ed1
@bigstair/core:build: cache bypass, force executing dfe08ca6290d77c8
@bigstair/core:build: $ tsup --format esm,cjs --dts --external react
@bigstair/core:dev: $ tsup --format esm,cjs --watch --dts --external react
@bigstair/core:build: CLI Building entry: src/index.ts, src/dropdown/dropdown.tsx, src/dropdown/index.ts, src/dropdown/nested-menu-item.tsx, src/dropdown-search-text/dropdown-search-text.tsx, src/dropdown-search-text/filters.ts, src/dropdown-search-text/index.ts, src/dropdown-search-text/recent-searches.tsx
@bigstair/core:build: CLI Using tsconfig: tsconfig.json
@bigstair/core:build: CLI tsup v5.10.3
@bigstair/core:build: CLI Using tsup config: /Users/me/Developer/monorepo/packages/bigstair-core/tsup.config.json
@bigstair/core:build: CLI Target: node12
@bigstair/core:build: CLI Cleaning output folder
@bigstair/core:build: ESM Build start
@bigstair/core:build: CJS Build start
@bigstair/core:build: CJS Build success in 27ms
@bigstair/core:build: ESM Build success in 33ms
@bigstair/core:dev: CLI Building entry: src/index.ts, src/dropdown/dropdown.tsx, src/dropdown/index.ts, src/dropdown/nested-menu-item.tsx, src/dropdown-search-text/dropdown-search-text.tsx, src/dropdown-search-text/filters.ts, src/dropdown-search-text/index.ts, src/dropdown-search-text/recent-searches.tsx
@bigstair/core:dev: CLI Using tsconfig: tsconfig.json
@bigstair/core:dev: CLI tsup v5.10.3
@bigstair/core:dev: CLI Using tsup config: /Users/me/Developer/monorepo/packages/bigstair-core/tsup.config.json
@bigstair/core:dev: CLI Running in watch mode
@bigstair/core:dev: CLI Target: node12
@bigstair/core:dev: CLI Cleaning output folder
@bigstair/core:dev: ESM Build start
@bigstair/core:dev: CJS Build start
@bigstair/core:dev: CJS Build success in 26ms
@bigstair/core:dev: ESM Build success in 32ms
@bigstair/core:dev: CLI Watching for changes in "."
@bigstair/core:dev: CLI Ignoring changes in "**/{.git,node_modules}/**" | "dist"
@bigstair/core:build: DTS Build start
@bigstair/core:dev: DTS Build start
@bigstair/core:build: DTS Build success in 2968ms
@bigstair/form:build: cache bypass, force executing 92be96dbc2329e7e
@bigstair/form:dev: cache bypass, force executing 2ef3e9894f0962cd
@bigstair/form:build: $ tsup --format esm,cjs --dts --external react
@bigstair/form:dev: $ tsup --format esm,cjs --watch --dts --external react
@bigstair/form:build: CLI Building entry: src/index.ts
@bigstair/form:build: CLI Using tsconfig: tsconfig.json
@bigstair/form:build: CLI tsup v5.10.3
@bigstair/form:build: CLI Using tsup config: /Users/me/Developer/monorepo/packages/bigstair-form/tsup.config.json
@bigstair/form:build: CLI Target: node12
@bigstair/form:build: CLI Cleaning output folder
@bigstair/form:build: ESM Build start
@bigstair/form:build: CJS Build start
@bigstair/form:build: CJS Build success in 40ms
@bigstair/form:build: ESM Build success in 46ms
@bigstair/form:dev: CLI Building entry: src/index.ts
@bigstair/form:dev: CLI Using tsconfig: tsconfig.json
@bigstair/form:dev: CLI tsup v5.10.3
@bigstair/form:dev: CLI Using tsup config: /Users/me/Developer/monorepo/packages/bigstair-form/tsup.config.json
@bigstair/form:dev: CLI Running in watch mode
@bigstair/form:dev: CLI Target: node12
@bigstair/form:dev: CLI Cleaning output folder
@bigstair/form:dev: ESM Build start
@bigstair/form:dev: CJS Build start
@bigstair/form:dev: ESM Build success in 88ms
@bigstair/form:dev: CJS Build success in 80ms
@bigstair/form:dev: CLI Watching for changes in "."
@bigstair/form:dev: CLI Ignoring changes in "**/{.git,node_modules}/**" | "dist"
@bigstair/form:build: DTS Build start
@bigstair/form:dev: DTS Build start
@bigstair/core:dev: DTS Build success in 4575ms
@bigstair/form:dev: DTS Build success in 2903ms
@bigstair/form:build: src/form/form.tsx(10,51): error TS2306: File '/Users/me/Developer/monorepo/packages/bigstair-core/dist/index.d.ts' is not a module.
@bigstair/form:build: src/form/form.tsx(11,32): error TS2306: File '/Users/me/Developer/monorepo/packages/bigstair-core/dist/index.d.ts' is not a module.
@bigstair/form:build:
@bigstair/form:build: DTS Build error
@bigstair/form:build: Error: Failed to compile. Check the logs above.
@bigstair/form:build:     at error (/Users/me/Developer/monorepo/node_modules/rollup/dist/shared/rollup.js:198:30)
@bigstair/form:build:     at throwPluginError (/Users/me/Developer/monorepo/node_modules/rollup/dist/shared/rollup.js:21718:12)
@bigstair/form:build:     at Object.error (/Users/me/Developer/monorepo/node_modules/rollup/dist/shared/rollup.js:22672:20)
@bigstair/form:build:     at Object.error (/Users/me/Developer/monorepo/node_modules/rollup/dist/shared/rollup.js:21895:42)
@bigstair/form:build:     at Object.transform (/Users/me/Developer/monorepo/node_modules/tsup/dist/rollup.js:7112:20)
@bigstair/form:build:     at /Users/me/Developer/monorepo/node_modules/rollup/dist/shared/rollup.js:22879:40
@bigstair/form:build: src/form/form-controls/select-schedule-dialog/select-schedule-dialog.tsx(10,41): error TS2306: File '/Users/me/Developer/monorepo/packages/bigstair-core/dist/index.d.ts' is not a module.
@bigstair/form:build:
@bigstair/form:build: src/form/form-controls/image/image-upload-multiple/image-upload-multiple.tsx(12,30): error TS2306: File '/Users/me/Developer/monorepo/packages/bigstair-core/dist/index.d.ts' is not a module.
@bigstair/form:build:
@bigstair/form:build: error Command failed with exit code 1.
@bigstair/form:build: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@bigstair/form:build: command finished with error, but continuing..
```

[1]

```
{
  "$schema": "https://turborepo.org/schema.json",
  "pipeline": {
    "build": {
      "outputs": [
        "dist/**",
        ".next/**"
      ],
      "dependsOn": [
        "^build"
      ],
      "cache": false
    },
    "test": {
      "outputs": [
        "coverage/**"
      ],
      "dependsOn": []
    },
    "preview": {
      "outputs": []
    },
    "lint": {
      "outputs": []
    },
    "dev": {
      "dependsOn": [
        "^build"
      ],
      "cache": false
    },
    "clean": {
      "cache": false
    }
  }
}
```

### Expected Behavior

It should not be flaky.

### To Reproduce

-

### Reproduction Repo

Private Repository

**Comment by rwieruch** [comment]
I will open a new issue, because this one mixes two problems.

**Comment by kamalbennani** [comment]
Hi @rwieruch I'm facing the same issue, were you able to find a workaround for this?

**Comment by 9vfQbg7z4ajrGQxR** [comment]
Same issue @kamalbennani, @rwieruch did you find something ?
