### ISSUE TITLE
[turbopack] Using `next/font/local` crashes with "is not a function" error in Next13 with appDir

### ISSUE THREAD

**Issue by timfee** [vercel/turbo#4128]
### What version of Turbopack are you using?

Whatever is bundled with `next@13.2.4-canary.7`

### What package manager are you using / does the bug impact?

pnpm 7.29.1

### What operating system are you using?

Mac

### Describe the Bug

With a barebones Next.js 13 appDir setup, I get an error trying to use `next/font/local` as per documentation:

```tsx
// ./layout.tsx
import "./globals.css"
import localFont from "next/font/local"

const Serif = localFont({
  display: "swap",
  preload: true,
  variable: "--font-serif",
  src: [
    {
      path: "../public/fonts/serif-regular.woff2",
      weight: "400",
      style: "normal",
    },
    // snip
  ]
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${Serif.variable} antialiased`}>
      <body>
        <main className="font-serif">{children}</main>
      </body>
    </html>
  )
}
```
```tsx
// ./page.tsx
export default function Home() {
  return <>look, Serif</>
}
```

This works fine with `npx next dev` but breaks with `npx next dev --turbo`:

<img width="1388" alt="Screen Shot 2023-03-08 at 13 13 18" src="https://user-images.githubusercontent.com/3246342/223852096-bd9f7039-0df0-4d64-ab1c-30eefab96c9d.png">

I could have _sworn_ I read that `next/font/local` breaks Turbopack in the past, but don't see any caveats, so am not sure if this is a KP.

<details><summary>Detailed stacktrace</summary>

```
error - [rendering] [root of the server]/  Error during SSR Rendering
  TypeError: __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f2e$pnpm$2f$next$40$13$2e$2$2e$4$2d$canary$2e$7_biqbaboplfbrettd7655fr4n2y$2f$node_modules$2f$next$2f$font$2f$local$2f$index$2e$js__$28$ecmascript$29__.default is not a function
    at <unknown> (.next/server/app/chunks/rsc/_a52c2f._.js:14:239)
    at [project]/app/layout.tsx (ecmascript, rsc) (.next/server/app/chunks/rsc/_a52c2f._.js:86:3)
    at <unknown> (.next/server/app/chunks/ssr/_9649cc._.js:73539:19)
    at runModuleExecutionHooks (.next/server/app/chunks/ssr/_9649cc._.js:73579:3)
    at instantiateModule (.next/server/app/chunks/ssr/_9649cc._.js:73538:3)
    at getOrInstantiateModuleFromParent (.next/server/app/chunks/ssr/_9649cc._.js:73621:10)
    at esmImport (.next/server/app/chunks/ssr/_9649cc._.js:73364:18)
    at <unknown> (.next/server/app/chunks/rsc/[next]_entry_app_layout-entry.tsx_7e2ba0._.js:24:97)
    at [next]/entry/app/layout-entry.tsx/(PAGE)/[project]/app/layout.tsx (ecmascript) (ecmascript, rsc) (.next/server/app/chunks/rsc/[next]_entry_app_layout-entry.tsx_7e2ba0._.js:38:3)
    at <unknown> (.next/server/app/chunks/ssr/_9649cc._.js:73539:19)
    at runModuleExecutionHooks (.next/server/app/chunks/ssr/_9649cc._.js:73579:3)
    at instantiateModule (.next/server/app/chunks/ssr/_9649cc._.js:73538:3)
    at getOrInstantiateModuleFromParent (.next/server/app/chunks/ssr/_9649cc._.js:73621:10)
    at esmImport (.next/server/app/chunks/ssr/_9649cc._.js:73364:18)
    at Module.default (.next/server/app/chunks/rsc/[next]_entry_app_layout-entry.tsx_7e2ba0._.js:42:20)
    at <unknown> (.next/server/app/chunks/ssr/_9649cc._.js:39:216)
    at [project]/app/entry (ecmascript, ssr) (.next/server/app/chunks/ssr/_9649cc._.js:253:3)
    at <unknown> (.next/server/app/chunks/ssr/_9649cc._.js:73539:19)
    at runModuleExecutionHooks (.next/server/app/chunks/ssr/_9649cc._.js:73579:3)
    at instantiateModule (.next/server/app/chunks/ssr/_9649cc._.js:73538:3)
    at instantiateRuntimeModule (.next/server/app/chunks/ssr/_9649cc._.js:74143:10)
    at <unknown> (.next/server/app/chunks/ssr/_9649cc._.js:73158:1)
    at <unknown> (.next/server/app/chunks/ssr/_9649cc._.js:74194:37)
    at <anonymous>
    at Object.registerChunk [as push] (.next/server/app/chunks/ssr/_9649cc._.js:74194:23)
    at Object.<anonymous> (.next/server/app/chunks/rsc/[next]_entry_app_layout-entry.tsx_668b28._.js:1:41)
    at Module._compile (node:internal/modules/cjs/loader:1275:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
    at Module.load (node:internal/modules/cjs/loader:1133:32)
    at Module._load (node:internal/modules/cjs/loader:972:12)
    at Module.require (node:internal/modules/cjs/loader:1157:19)
    at require (node:internal/modules/helpers:119:18)
    at Object.<anonymous> (.next/server/app/ec86698594537a52.js:16:1)
    at Module._compile (node:internal/modules/cjs/loader:1275:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
    at Module.load (node:internal/modules/cjs/loader:1133:32)
    at Module._load (node:internal/modules/cjs/loader:972:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at <unknown> (node:internal/main/run_main_module:23:47)
```

</details>

Environment:
```
    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.3.0: Mon Jan 30 20:38:37 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 19.7.0
      npm: 9.5.0
      Yarn: N/A
      pnpm: 7.29.1
    Relevant packages:
      next: 13.2.4-canary.7
      eslint-config-next: 13.2.3
      react: 18.2.0
      react-dom: 18.2.0
```

### Expected Behavior

Page renders properly.

### To Reproduce

See attached repo.

### Reproduction Repo

https://github.com/timfee/turbo-next-font-local-repro

**Comment by jridgewell** [comment]
Hi @timfee: `next/font/local` isn't currently implemented yet, but we're actively working on this for the next Next.js minor release.

**Comment by jridgewell** [comment]
Tracking internally as WEB-249
