### ISSUE TITLE
[WEB-819] [turborepo] 1.8.8 not working

### ISSUE THREAD

**Issue by semmywong** [vercel/turbo#4395]
### What version of Turborepo are you using?

1.8.8

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Windows

### Describe the Bug

1. run `pnpm dlx create-turbo@latest`, then create new monorepo
2. `cd ./my-turborepo` and run `pnpm dev`

error:
> my-turborepo@0.0.0 dev D:\WorkStudio\demo\nx-test\my-turborepo
> turbo run dev

D:\WorkStudio\demo\nx-test\my-turborepo\node_modules\.pnpm\turbo@1.8.8\node_modules\turbo\bin\turbo:13
    throw e;
    ^

Error: Cannot find module 'turbo'
Require stack:
- D:\WorkStudio\demo\nx-test\my-turborepo\node_modules\.pnpm\turbo@1.8.8\node_modules\turbo\node-platform.js
- D:\WorkStudio\demo\nx-test\my-turborepo\node_modules\.pnpm\turbo@1.8.8\node_modules\turbo\bin\turbo
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:931:15)
    at Function.resolve (internal/modules/cjs/helpers.js:113:19)
    at downloadedBinPath (D:\WorkStudio\demo\nx-test\my-turborepo\node_modules\.pnpm\turbo@1.8.8\node_modules\turbo\node-platform.js:47:44)
    at generateBinPath (D:\WorkStudio\demo\nx-test\my-turborepo\node_modules\.pnpm\turbo@1.8.8\node_modules\turbo\node-platform.js:98:15)
    at Object.<anonymous> (D:\WorkStudio\demo\nx-test\my-turborepo\node_modules\.pnpm\turbo@1.8.8\node_modules\turbo\bin\turbo:7:5)
    at Module._compile (internal/modules/cjs/loader.js:1114:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\WorkStudio\\demo\\nx-test\\my-turborepo\\node_modules\\.pnpm\\turbo@1.8.8\\node_modules\\turbo\\node-platform.js',
    'D:\\WorkStudio\\demo\\nx-test\\my-turborepo\\node_modules\\.pnpm\\turbo@1.8.8\\node_modules\\turbo\\bin\\turbo'
  ]
}
 ELIFECYCLE  Command failed with exit code 1.

### Expected Behavior

Can be started normally

### To Reproduce

`pnpm dlx create-turbo@latest`

<sub>[WEB-819](https://linear.app/vercel/issue/WEB-819/[turborepo])</sub>

**Comment by tknickman** [comment]
Hey @semmywong, do you see the same behavior with 1.8.6?

**Comment by NicholasLYang** [comment]
Hey, I noticed that the path for your node_modules is `node_modules.pnpm` in the require stack. Is that correct?

**Comment by semmywong** [comment]
> Hey @semmywong, do you see the same behavior with 1.8.6?

working fine in 1.8.6.

**Comment by semmywong** [comment]
> Hey, I noticed that the path for your node_modules is `node_modules.pnpm` in the require stack. Is that correct?

This is not a problem, this is a github escaping problem, the content I copied up was escaped

![image](https://user-images.githubusercontent.com/67748948/229048958-89e81746-21e3-46b1-ba6d-34c13ba50fa8.png)

**Comment by NicholasLYang** [comment]
Gotcha @semmywong. I'm having trouble reproducing this. What version of pnpm are you using?

**Comment by semmywong** [comment]
> Gotcha @semmywong. I'm having trouble reproducing this. What version of pnpm are you using?

pnpm is 7.30.0
