### ISSUE TITLE
[turborepo] migrate-env-var-dependencies codemod fails with error: TypeError: Za(...).map is not a function

### ISSUE THREAD

**Issue by graup** [vercel/turbo#4469]
### What version of Turborepo are you using?

1.8.8

### What package manager are you using / does the bug impact?

Yarn v2/v3 (node_modules linker only)

### What operating system are you using?

Mac

### Describe the Bug

```
npx @turbo/codemod migrate-env-var-dependencies
? Where is the root of the repo where the transform should run? .
 INFO  Migrating environment variable dependencies from "globalDependencies" and "dependsOn" to "env" in "turbo.json"...

Unexpected error. Please report it as a bug:
TypeError: Za(...).map is not a function
    at za (/Users/paulgrau/.npm/_npx/b5f7626c653117ba/node_modules/@turbo/codemod/dist/transforms/migrate-env-var-dependencies.js:52:1169)
    at Object.ni [as transformer] (/Users/paulgrau/.npm/_npx/b5f7626c653117ba/node_modules/@turbo/codemod/dist/transforms/migrate-env-var-dependencies.js:56:17017)
    at Command.L (/Users/paulgrau/.npm/_npx/b5f7626c653117ba/node_modules/@turbo/codemod/dist/cli.js:6:29)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Command.parseAsync (/Users/paulgrau/.npm/_npx/b5f7626c653117ba/node_modules/commander/lib/command.js:935:5)
```

### Expected Behavior

No error

### To Reproduce

Our turbo.json looks like this:

```
{
  "baseBranch": "origin/main",
  "pipeline": {
    "build": {
      "dependsOn": ["^build"],
      "outputs": ["dist/**", ".next/**"]
    },
    "lint": {
      "dependsOn": ["^build"],
      "outputs": []
    },
    "format": {
      "dependsOn": [],
      "outputs": []
    },
    "test": {
      "dependsOn": ["^build"],
      "outputs": []
    },
    "dev": {
      "dependsOn": ["^build"],
      "cache": false
    },
    "storybook": {
      "cache": false
    },
    "product-test#build": {
      "dependsOn": ["^build"],
      "outputs": [".next/**"]
    },
    "product#build": {
      "dependsOn": [
        "^build",
        "$APP_ENV",
        "$VERCEL_ENV",
        "$VERCEL_GIT_COMMIT_REF",
      ],
      "outputs": [".next/**"]
    }
  }
}

```

**Comment by tknickman** [comment]
Hey @graup, thanks for the report, we have a similar bug with the eslint-plugin (https://github.com/vercel/turbo/issues/4085) so this is helpful to track down the source!

If you have the time to create a minimal reproduction to share that would be awesome, but no worries if not, I should be able to take a look at this soon!
