### ISSUE TITLE
[turborepo] Panic

### ISSUE THREAD

**Issue by hansottowirtz** [vercel/turbo#4487]
### What version of Turborepo are you using?

1.8.5

### What package manager are you using / does the bug impact?

Yarn v2/v3 (node_modules linker only)

### What operating system are you using?

Mac

### Describe the Bug

After many hours of running a Next.js project in dev mode, Turbo sometimes panics while Next.js is compiling.

It's not a big issue, but it has happened multiple times.

```
web:dev: event - compiled successfully in 1476 ms (2304 modules)
web:dev: warn  - Fast Refresh had to perform a full reload. Read more: https://nextjs.org/docs/messages/fast-refresh-reload
web:dev: wait  - compiling...
web:dev: thread '<unnamed>' panicked at 'assertion failed: start <= end', /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_common-0.29.37/src/input.rs:31:9
web:dev: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
web:dev: fatal runtime error: failed to initiate panic, error 5
web:dev: 

 Tasks:    1 successful, 1 total
Cached:    0 cached, 1 total
  Time:    22h47m20.734s
```

### Expected Behavior

Turbo shouldn't crash.

### To Reproduce

/

**Comment by NicholasLYang** [comment]
Thanks for the issue! I'm not sure this is turborepo, since we don't use swc as far as I can tell. It might be turbopack or next.js. I'll see if I can ping someone for this. In the meanwhile, could you try running with the `RUST_BACKTRACE=1` environment variable set?

**Comment by padmaia** [comment]
Yeah, this is a turbopack issue. Will investigate.

**Comment by hansottowirtz** [comment]
It might be a Next.js issue after all, because I didn't enable turbopack but I have `experimental.forceSwcTransforms` set to true.

**Comment by kdy1** [comment]
I think this is because `swc_common::SourceMap` does not drop old files.
Not sure about the fix at the moment, though

**Comment by hansottowirtz** [comment]
Setting `RUST_BACKTRACE=1` doesn't give any more useful information, unfortunately.

**Comment by hansottowirtz** [comment]
with `RUST_BACKTRACE=full`:
```
web:dev: thread '<unnamed>' panicked at 'assertion failed: start <= end', /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_common-0.29.37/src/input.rs:31:9
web:dev: stack backtrace:
web:dev:    0:        0x133d41924 - _napi_register_module_v1
web:dev:    1:        0x133d62b30 - _napi_register_module_v1
web:dev:    2:        0x133d3d528 - _napi_register_module_v1
web:dev:    3:        0x133d41738 - _napi_register_module_v1
web:dev:    4:        0x133d43000 - _napi_register_module_v1
web:dev:    5:        0x133d42d58 - _napi_register_module_v1
web:dev:    6:        0x133d43510 - _napi_register_module_v1
web:dev:    7:        0x133d43404 - _napi_register_module_v1
web:dev:    8:        0x133d41d44 - _napi_register_module_v1
web:dev:    9:        0x133d431a0 - _napi_register_module_v1
web:dev:   10:        0x133e9cbe4 - _napi_register_module_v1
web:dev:   11:        0x133e9cc54 - _napi_register_module_v1
web:dev:   12:        0x133c54434 - _wasmer_vm_raise_trap
web:dev:   13:        0x133b27404 - _wasmer_vm_raise_trap
web:dev:   14:        0x132bbb608 - _BrotliDecoderVersion
web:dev:   15:        0x132bbefd4 - _BrotliDecoderVersion
web:dev:   16:        0x13028ffbc - <unknown>
web:dev:   17:        0x13035662c - <unknown>
web:dev:   18:        0x1302aad88 - <unknown>
web:dev:   19:        0x103171168 - _worker
web:dev:   20:        0x1aee95240 - __pthread_deallocate
web:dev: fatal runtime error: failed to initiate panic, error 5
```
