### ISSUE TITLE
[turbopack] "TypeError: (ecmascript)}.cache is not a function" after adding `zod` and `react-hook-form` with `@hookform/resolvers` to the project

### ISSUE THREAD

**Issue by MartinXPN** [vercel/turbo#5103]
### What version of Next.js are you using Turbopack in?

13.4.3

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Mac

### Describe the Bug

After adding 3 packages to manage forms (namely `zod`, `react-hook-form`, and `@hookform/resolvers`) the app wouldn't work at all. It works fine without `--turbo`. Gives the following error with `--turbo` enabled:
```
Caused by:
- TypeError: {imported module [project]/node_modules/react/index.js (ecmascript)}.cache is not a function

Debug info:
- Execution of get_from_source failed
- Execution of resolve_source_request failed
- Execution of NextRouterContentSource::get failed
- error during Next.js routing for /login
- TypeError: {imported module [project]/node_modules/react/index.js (ecmascript)}.cache is not a function
      [at file:///***/.next/build/edge/chunks/[next]_entry_edge-bootstrap.ts_9def4b._.js]
      [at file:///****/.next/build/edge/chunks/middleware.ts_8ee95b._.js:29:132]
      [at [project]/src/app/auth/getUser.ts (ecmascript) (file:///***/.next/build/edge/chunks/middleware.ts_8ee95b._.js:46:3)]
      [at file:///***/.next/build/edge/chunks/[next]_entry_edge-bootstrap.ts_9def4b._.js:497:21]
      [at runModuleExecutionHooks (file:///***/.next/build/edge/chunks/[next]_entry_edge-bootstrap.ts_9def4b._.js:544:5)]
      [at instantiateModule (file:///***/.next/build/edge/chunks/[next]_entry_edge-bootstrap.ts_9def4b._.js:496:5)]
      [at getOrInstantiateModuleFromParent (file:///***/.next/build/edge/chunks/[next]_entry_edge-bootstrap.ts_9def4b._.js:593:10)]
      [at esmImport (file:///***/.next/build/edge/chunks/[next]_entry_edge-bootstrap.ts_9def4b._.js:217:18)]
      [at file:///***/.next/build/edge/chunks/middleware.ts_8ee95b._.js:55:113]
      [at [project]/middleware.ts (ecmascript, ecmascript) (file:///***/.next/build/edge/chunks/middleware.ts_8ee95b._.js:130:3)]
      [at file:///***/.next/build/edge/chunks/[next]_entry_edge-bootstrap.ts_9def4b._.js:497:21]
```

### Expected Behavior

Would be great if the app wouldn't crash.

### To Reproduce

```json
  "dependencies": {
    "@emotion/react": "^11.11.0",
    "@emotion/styled": "^11.11.0",
    "@hookform/resolvers": "^3.1.0",
    "@mui/icons-material": "^5.11.16",
    "@mui/material": "^5.13.2",
    "@types/node": "20.2.3",
    "@types/react": "18.2.6",
    "@types/react-dom": "18.2.4",
    "encoding": "^0.1.13",
    "eslint": "8.41.0",
    "eslint-config-next": "13.4.3",
    "firebase": "^9.22.0",
    "next": "13.4.3",
    "next-firebase-auth-edge": "^0.7.5",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-drag-drop-files": "^2.3.10",
    "react-hook-form": "^7.43.9",
    "typescript": "5.0.4",
    "use-async-effect": "^2.2.7",
    "zod": "^3.21.4"
  }
```

**Comment by MartinXPN** [comment]
Just tried with the latest version (13.4.4) and got the same results:
```
  "dependencies": {
    "@emotion/react": "^11.11.0",
    "@emotion/styled": "^11.11.0",
    "@hookform/resolvers": "^3.1.0",
    "@mui/icons-material": "^5.11.16",
    "@mui/material": "^5.13.2",
    "@types/node": "20.2.4",
    "@types/react": "18.2.7",
    "@types/react-dom": "18.2.4",
    "encoding": "^0.1.13",
    "eslint": "8.41.0",
    "eslint-config-next": "13.4.4",
    "firebase": "^9.22.1",
    "next": "13.4.4",
    "next-firebase-auth-edge": "^0.7.5",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-drag-drop-files": "^2.3.10",
    "react-hook-form": "^7.43.9",
    "typescript": "5.0.4",
    "use-async-effect": "^2.2.7",
    "zod": "^3.21.4"
  }
  ```

**Comment by timneutkens** [comment]
Can you give it another try with `next@canary` (`npm install next@canary`) the Next.js test suite is almost entirely passing now. Thanks in advance!

**Comment by ForsakenHarmony** [comment]
Closing as it was pre nexturbo (feel free to create a new issue in the next.js repo though)
