### ISSUE TITLE
[turborepo] codemod update fails 

### ISSUE THREAD

**Issue by chandlervdw** [vercel/turbo#5167]
### What version of Turborepo are you using?

v1.9.9

### What package manager are you using / does the bug impact?

Yarn v2/v3 (node_modules linker only)

### What operating system are you using?

Mac

### Describe the Bug

When attempting to update to `v1.10.1`, running `npx @turbo/codemod update` fails with the following error:
```
Upgrading turbo from 1.9.9 to 1.10.1 (2 required codemods) 

(1/2) Running stabilize-env-mode
 INFO  Rewriting `experimentalPassThroughEnv` and `experimentalGlobalPassThroughEnv` 

Unexpected error. Please report it as a bug:
SyntaxError: turbo.json: Unexpected token / in JSON at position 626
    at JSON.parse (<anonymous>)
    at Object.readFileSync (/Users/chandler/.npm/_npx/b5f7626c653117ba/node_modules/jsonfile/index.js:52:17)
    at Object.Os [as transformer] (/Users/chandler/.npm/_npx/b5f7626c653117ba/node_modules/@turbo/codemod/dist/transforms/stabilize-env-mode.js:84:6669)
    at /Users/chandler/.npm/_npx/b5f7626c653117ba/node_modules/@turbo/codemod/dist/cli.js:4:7717
    at Array.map (<anonymous>)
    at Command.S (/Users/chandler/.npm/_npx/b5f7626c653117ba/node_modules/@turbo/codemod/dist/cli.js:4:7621)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Command.parseAsync (/Users/chandler/.npm/_npx/b5f7626c653117ba/node_modules/commander/lib/command.js:935:5)
```

### Expected Behavior

codemod update script should run successfully

### To Reproduce

run `npx @turbo/codemod update` from v1.9.9

**Comment by chandlervdw** [comment]
I determined that the issue was caused by a comment in my `turbo.json` file.
