### ISSUE TITLE
[turborepo] `npx @turbo/codemod update` throws error

### ISSUE THREAD

**Issue by kirkstrobeck** [vercel/turbo#5653]
### What version of Turborepo are you using?

1.10.7

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

```sh
npx @turbo/codemod update
? Where is the root of the repo to migrate? .
No codemods required to migrate from 1.10.7 to 1.10.12

Upgrading turbo from 1.10.7 to 1.10.12 (no codemods required)

Upgrading turbo with pnpm install turbo@latest --save-dev -w


Unexpected error. Please report it as a bug:
Error: Command failed: pnpm install turbo@latest --save-dev -w
    at checkExecSyncError (node:child_process:885:11)
    at execSync (node:child_process:957:15)
    at Command.N (/Users/username/.npm/_npx/b5f7626c653117ba/node_modules/@turbo/codemod/dist/cli.js:4:8282)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Command.parseAsync (/Users/kstrobeck/.npm/_npx/b5f7626c653117ba/node_modules/commander/lib/command.js:935:5) {
  status: 1,
  signal: null,
  output: [
    null,
    <Buffer 50 72 6f 67 72 65 73 73 3a 20 72 65 73 6f 6c 76 65 64 20 31 2c 20 72 65 75 73 65 64 20 30 2c 20 64 6f 77 6e 6c 6f 61 64 65 64 20 30 2c 20 61 64 64 65 ... 4647 more bytes>,
    <Buffer >
  ],
  pid: 27670,
  stdout: <Buffer 50 72 6f 67 72 65 73 73 3a 20 72 65 73 6f 6c 76 65 64 20 31 2c 20 72 65 75 73 65 64 20 30 2c 20 64 6f 77 6e 6c 6f 61 64 65 64 20 30 2c 20 61 64 64 65 ... 4647 more bytes>,
  stderr: <Buffer >
}


A new version of `@turbo/codemod` is available!
You can update by running: pnpm i -g @turbo/codemod
```

### Expected Behavior

Successful upgrade

### To Reproduce

`npx @turbo/codemod update`

### Reproduction Repo

n/a

**Comment by dBianchii** [comment]
Happenes to me as well! Was going to create an issue, but someone beat me to it :)

**Comment by tknickman** [comment]
Hey @dBianchii! We just landed a pretty significant refactor of `update` (in this [PR](https://github.com/vercel/turbo/pull/5279)) aimed at fixing these issues. It's not landed in a release yet, but should hit canary very soon. I'll let you know when it's available to test!

**Comment by tknickman** [comment]
@dBianchii & @kirkstrobeck can you give `@turbo/codemod@canary` a shot and let me know if it's solved your issue?

**Comment by dBianchii** [comment]
> @turbo/codemod@canary

Hi @tknickman. Sure thing. Here's my console result, after running `npx @turbo/codemod@canary update` in the terminal:

```terminal
$ npx @turbo/codemod@canary update
Debugger listening on ws://127.0.0.1:61353/e71203b7-d02e-46de-a61c-d62fd6a106a8
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
Waiting for the debugger to disconnect...
Need to install the following packages:
  @turbo/codemod@1.10.13-canary.0
Ok to proceed? (y) y
npm WARN deprecated cross-spawn-async@2.2.5: cross-spawn no longer requires a build toolchain, use it instead
? Where is the root of the repo to migrate? .
No codemods required to migrate from 1.10.7 to 1.10.12 

Upgrading turbo from 1.10.7 to 1.10.12 (no codemods required) 

Upgrading turbo with pnpm add turbo@latest --global 

Migration completed
```

Looks like it works! Thank you!

**Comment by kirkstrobeck** [comment]
Works

**Comment by tknickman** [comment]
Released
