### ISSUE TITLE
[turborepo] prettier doesn't work in turbo project on both Vscode and Webstorm

### ISSUE THREAD

**Issue by sotatek-kinn** [vercel/turbo#5835]
### What version of Turborepo?

1.10.12

### What package manager does the bug impact?

yarn@1.22.19

### What operating system?

Ubuntu 22.04
Windows 10 

### Describe the Bug

I can't not format the code with prettier like normal

Tools:
 - Webstorm (2023.1.2)
 - Vscode (1.81.1)
 
Step:  
1. npx create-turbo -e basic
2. Using Shift + Alt + F (vscode) to format document `apps/docs/app/layout.tsx` => Fail
3. Using Ctrl + Shift + Alt + P (webstorm) to format file `apps/docs/app/layout.tsx` => Fail
4. Open terminal then yarn format => OK

### Expected Behavior

The file should have correct format after formatting such as using `yarn format`

### To Reproduce
Repo: https://github.com/sotatek-kinn/turbo-prettier
**package.json**
```
{
  "private": true,
  "scripts": {
    "build": "turbo run build",
    "dev": "turbo run dev",
    "lint": "turbo run lint",
    "format": "prettier --write \"**/*.{ts,tsx,md}\""
  },
  "devDependencies": {
    "eslint": "^8.48.0",
    "prettier": "^3.0.3",
    "tsconfig": "*",
    "turbo": "latest"
  },
  "name": "turborepo-base",
  "packageManager": "yarn@1.22.19",
  "workspaces": [
    "apps/*",
    "packages/*"
  ]
}
```

Error in webstorm
![image](https://github.com/vercel/turbo/assets/115981018/4454acf2-5d5a-4c88-be5a-27b83324aa36)

Error in vscode
![image](https://github.com/vercel/turbo/assets/115981018/42a25bd1-3cb6-4d42-9112-eb6242b8050c)

**Comment by sotatek-kinn** [comment]
```
{
  "private": true,
  "scripts": {
    "build": "turbo run build",
    "dev": "turbo run dev",
    "lint": "turbo run lint",
    "format": "prettier --write \"**/*.{ts,tsx,md}\""
  },
  "devDependencies": {
    "eslint": "^8.48.0",
    "prettier": "^3.0.3",
    "tsconfig": "*",
    "turbo": "latest"
  },
  "name": "turborepo-base",
  "packageManager": "yarn@1.22.19",
  "workspaces": [
    "apps/*",
    "packages/*"
  ]
}

```

**Comment by sotatek-kinn** [comment]
Hi @tknickman, this is all you ask about

Vscode version:
![Screenshot from 2023-09-03 15-31-16](https://github.com/vercel/turbo/assets/115981018/49eefd24-a381-4d6c-b90e-98380eac6d45)

Webstorm version:
![Screenshot from 2023-09-03 15-32-50](https://github.com/vercel/turbo/assets/115981018/79a9c742-2aa6-432b-8900-4784c9c24bc5)

Repo:
https://github.com/sotatek-kinn/turbo-prettier

**Comment by wukong-c** [comment]
Any progress on this please, I'm experiencing the same situation

**Comment by DeVoresyah** [comment]
same issue on vscode

**Comment by anthonyshew** [comment]
Are folks still seeing this problem? We've done some work on our examples since the reports I'm seeing here and I'm not able to reproduce the issue.

**Comment by anthonyshew** [comment]
@satishkumarsajjan I'm seeing yarn Berry there. Do you see the same problem with a different package manager?

**Comment by TudorEsan** [comment]
same issue with pnpm , getting this errros:
```
["INFO" - 22:56:47] Formatting file:///Users/tudoresan/Desktop/starknet/turborepo-shadcn-ui/package.json
["ERROR" - 22:56:47] Error resolving prettier configuration for /Users/tudoresan/Desktop/starknet/turborepo-shadcn-ui/package.json
["ERROR" - 22:56:47] Error loading node module '/Users/tudoresan/Desktop/starknet/turborepo-shadcn-ui/node_modules/prettier/index.cjs'
Error: Error loading node module '/Users/tudoresan/Desktop/starknet/turborepo-shadcn-ui/node_modules/prettier/index.cjs'
    at t.loadNodeModule (/Users/tudoresan/.vscode/extensions/esbenp.prettier-vscode-10.4.0/dist/extension.js:1:2848)
    at t.PrettierMainThreadInstance.import (/Users/tudoresan/.vscode/extensions/esbenp.prettier-vscode-10.4.0/dist/extension.js:1:17964)
    at t.PrettierMainThreadInstance.resolveConfigFile (/Users/tudoresan/.vscode/extensions/esbenp.prettier-vscode-10.4.0/dist/extension.js:1:18661)
    at t.ModuleResolver.resolveConfig (/Users/tudoresan/.vscode/extensions/esbenp.prettier-vscode-10.4.0/dist/extension.js:1:6856)
    at t.ModuleResolver.getResolvedConfig (/Users/tudoresan/.vscode/extensions/esbenp.prettier-vscode-10.4.0/dist/extension.js:1:7735)
    at t.default.format (/Users/tudoresan/.vscode/extensions/esbenp.prettier-vscode-10.4.0/dist/extension.js:1:14767)
    at t.PrettierEditProvider.provideEdits (/Users/tudoresan/.vscode/extensions/esbenp.prettier-vscode-10.4.0/dist/extension.js:1:12876)
["ERROR" - 22:56:53] Error handling text editor change
["ERROR" - 22:56:53] Invalid version
Error: Invalid version
    at t.isAboveV3 (/Users/tudoresan/.vscode/extensions/esbenp.prettier-vscode-10.4.0/dist/extension.js:1:24917)
    at t.default.getSelectors (/Users/tudoresan/.vscode/extensions/esbenp.prettier-vscode-10.4.0/dist/extension.js:1:11745)
    at t.default.handleActiveTextEditorChanged (/Users/tudoresan/.vscode/extensions/esbenp.prettier-vscode-10.4.0/dist/extension.js:1:11131)
["ERROR" - 22:56:55] Error handling text editor change
["ERROR" - 22:56:55] Invalid version
Error: Invalid version
    at t.isAboveV3 (/Users/tudoresan/.vscode/extensions/esbenp.prettier-vscode-10.4.0/dist/extension.js:1:24917)
    at t.default.getSelectors (/Users/tudoresan/.vscode/extensions/esbenp.prettier-vscode-10.4.0/dist/extension.js:1:11745)
    at t.default.handleActiveTextEditorChanged (/Users/tudoresan/.vscode/extensions/esbenp.prettier-vscode-10.4.0/dist/extension.js:1:11131)
["ERROR" - 22:57:35] Error handling text editor change
["ERROR" - 22:57:35] Invalid version
Error: Invalid version
    at t.isAboveV3 (/Users/tudoresan/.vscode/extensions/esbenp.prettier-vscode-10.4.0/dist/extension.js:1:24917)
    at t.default.getSelectors (/Users/tudoresan/.vscode/extensions/esbenp.prettier-vscode-10.4.0/dist/extension.js:1:11745)
    at t.default.handleActiveTextEditorChanged (/Users/tudoresan/.vscode/extensions/esbenp.prettier-vscode-10.4.0/dist/extension.js:1:11131)

```

**Comment by TudorEsan** [comment]
after restarting vs code prettier works again

**Comment by anthonyshew** [comment]
Going to close here as this is looking stale. If anyone starts seeing this problem again, please do open a fresh issue.
