### ISSUE TITLE
[turborepo] - React Native Template outdated 

### ISSUE THREAD

**Issue by williamlmao** [vercel/turbo#6015]
### What version of Turborepo are you using?

latest

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

https://github.com/vercel/turbo/tree/main/examples/with-react-native-web

This with-react-native-web example no longer works out of the box. The expo go says the expo version needs to be updated to 49, but after updating to that there are other errors. 

```
● Validation Warning:

  Unknown option "watcher" with value {"additionalExts": ["env.development.local", "env.local", "env.development", "env"]} was found.
  This is probably a typing mistake. Fixing it will remove this message.

Starting Metro Bundler
TypeError: runner.metro.getBundler(...).getBundler(...).getWatcher is not a function
```

Unfortunately I'm too new to react-native and expo to know how to troubleshoot this. 

### Expected Behavior

Template works out of the box

### To Reproduce

npx create-turbo@latest -e with-react-native-web

go to the native app folder

pnpm run ios

**Comment by peladno** [comment]
did you try using expo doctor?

**Comment by mehulkar** [comment]
I tried to reproduce this, but after installing XCode and agreeing to terms, I ran into:

```
➜  native git:(main) ✗ pnpm run ios

> native@1.0.0 ios /Users/mehulkar/dev/vercel/playground/issue-6015/apps/native
> expo start --ios

WARNING: The legacy expo-cli does not support Node +17. Migrate to the new local Expo CLI: https://blog.expo.dev/the-new-expo-cli-f4250d8e3421.
┌───────────────────────────────────────────────────────────────────────────┐
│                                                                           │
│   The global expo-cli package has been deprecated.                        │
│                                                                           │
│   The new Expo CLI is now bundled in your project in the expo package.    │
│   Learn more: https://blog.expo.dev/the-new-expo-cli-f4250d8e3421.        │
│                                                                           │
│   To use the local CLI instead (recommended in SDK 46 and higher), run:   │
│   › npx expo <command>                                                    │
│                                                                           │
└───────────────────────────────────────────────────────────────────────────┘
Starting project at /Users/mehulkar/dev/vercel/playground/issue-6015/apps/native
Some dependencies are incompatible with the installed expo package version:
 - react - expected version: 17.0.2 - actual version installed: 18.2.0
 - react-dom - expected version: 17.0.2 - actual version installed: 18.2.0
 - react-native-web - expected version: 0.17.7 - actual version installed: 0.18.12
Your project may not work correctly until you install the correct versions of the packages.
To install the correct versions of these packages, please run: expo doctor --fix-dependencies,
or install individual packages by running expo install [package-name ...]
Starting Metro Bundler
No iOS devices available in Simulator.app
Error: No iOS devices available in Simulator.app
    at getBestUnbootedSimulatorAsync (/Users/mehulkar/.nvm/versions/node/v18.18.0/lib/node_modules/expo-cli/node_modules/xdl/src/Simulator.ts:284:11)
    at ensureSimulatorOpenAsync (/Users/mehulkar/.nvm/versions/node/v18.18.0/lib/node_modules/expo-cli/node_modules/xdl/src/Simulator.ts:231:12)
    at Object.openProjectAsync (/Users/mehulkar/.nvm/versions/node/v18.18.0/lib/node_modules/expo-cli/node_modules/xdl/src/Simulator.ts:889:14)
    at /Users/mehulkar/.nvm/versions/node/v18.18.0/lib/node_modules/expo-cli/src/commands/utils/urlOpts.ts:124:18
    at async Promise.all (index 1)
    at handleMobileOptsAsync (/Users/mehulkar/.nvm/versions/node/v18.18.0/lib/node_modules/expo-cli/src/commands/utils/urlOpts.ts:105:19)
 ELIFECYCLE  Command failed with exit code 1.

```

**Comment by achadee** [comment]
Also running into this issue

**Comment by hatewx** [comment]
I've also encountered this issue.

**Comment by hit2hat** [comment]
+1
any updates?

**Comment by zowebs** [comment]
+1
Even tried to create new native app in `apps` folder using https://docs.expo.dev/guides/monorepos/ but did not help

**Comment by mehulkar** [comment]
This example was updated in https://github.com/vercel/turbo/pull/6572, check out if that helped!

**Comment by arlyon** [comment]
I can confirm that the react native web example works with the hoisted node linker (if you are using pnpm). 

https://pnpm.io/npmrc#node-linker

If that is not the case for you comment and I will re-open
