### ISSUE TITLE
[turbopack] - PageNotFoundError

### ISSUE THREAD

**Issue by Vincent-Lavallee** [vercel/turbo#6106]
### What version of Turborepo are you using?

Next V13.5.4 Also tried on 14.0.2

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Windows

### Describe the Bug

when runnning `next dev --turbo` I get this error 
```
⨯ PageNotFoundError: Cannot find module for page: route not found /
    at Object.ensurePage (/home/vincent/Warp/gold-frontend/node_modules/next/dist/server/lib/router-utils/setup-dev.js:825:27)
    at async Object.ensurePage (/home/vincent/Warp/gold-frontend/node_modules/next/dist/server/lib/router-server.js:87:24)
    at async DevServer.ensurePage (/home/vincent/Warp/gold-frontend/node_modules/next/dist/server/dev/next-dev-server.js:510:9)
    at async Object.ensure (/home/vincent/Warp/gold-frontend/node_modules/next/dist/server/dev/next-dev-server.js:163:17)
    at async DevRouteMatcherManager.matchAll (/home/vincent/Warp/gold-frontend/node_modules/next/dist/server/future/route-matcher-managers/dev-route-matcher-manager.js:94:13)
    at async DevRouteMatcherManager.match (/home/vincent/Warp/gold-frontend/node_modules/next/dist/server/future/route-matcher-managers/default-route-matcher-manager.js:159:26)
    at async DevServer.handleCatchallRenderRequest (/home/vincent/Warp/gold-frontend/node_modules/next/dist/server/next-server.js:567:27)
    at async DevServer.handleRequestImpl (/home/vincent/Warp/gold-frontend/node_modules/next/dist/server/base-server.js:728:17) {
  code: 'ENOENT'
}
```

### Expected Behavior

it's  working without turbo. I was also able to reproduce under WSL with ubuntu 22.04.

### To Reproduce

We're still using the pages directory. If I delete index.page.tsx at the root of the pages directory I don't get the error and I get the 404 page instead. If I go to any other page in my directory eg: login I get the same error.

I can give a slimmed down version of our app with only the pages directory if this helps

**Comment by GagikNav** [comment]
I have the same issue

**Comment by leonard-henriquez** [comment]
Me too

**Comment by sKopheK** [comment]
happing to me time to time with current next 16.2.7. never had this issue with webpack, switched from 14.2.35 last month
need to restart `dev` script to fix it
