### ISSUE TITLE
[turborepo] Many EPERM errors on Turbo Sveltekit, dev && build

### ISSUE THREAD

**Issue by MarArMar** [vercel/turbo#6137]
### What version of Turborepo are you using?

1.10.15

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Windows

### Describe the Bug

Very often (7 times out of 10) my local build or dev is blocked by the same "EPERM: operation not permitted, stat $types.d.ts" errors on Sveltekit build and sometime dev too

Bug first posted in Sveltekit but they mentioned it might be due to TurboRepo

https://github.com/sveltejs/kit/issues/10807

Error is :

    EPERM: operation not permitted, stat .../.svelte-kit/ ... /$types.d.ts

Makes dev experience really awful, I often have to run the same command 2 or 3 times or close / repopen VSCode

### Sometime - workaround 

Doing this seems like it somewhat reduces the occurences, only for build : 
```
Remove-Item -Recurse -Force 'apps\WingMan\.svelte-kit' ; npx turbo run build --filter=SvelteKitProject --no-daemon --no-update-notifier
```

### IDE 

VSCode with extensions : 
```
{
  "recommendations": [
    "christian-kohler.npm-intellisense",
    "christian-kohler.path-intellisense",
    "dbaeumer.vscode-eslint",
    "mhutchie.git-graph",
    "github.copilot",
    "github.copilot-chat",
    "github.copilot-labs",
    "esbenp.prettier-vscode",
    "rvest.vs-code-prettier-eslint",
    "pivaszbs.svelte-autoimport",
    "bradlc.vscode-tailwindcss"
  ]
}
```

TSConfig : 
```
{
  "extends": "./.svelte-kit/tsconfig.json",
  "compilerOptions": {
    "allowJs": true,
    "checkJs": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "sourceMap": true,
    "strict": true,
    "paths": {
      "$src/*": ["./src/*"],
      "$lib": ["./src/lib"],
      "$lib/*": ["./src/lib/*"],
      "$components": ["./src/lib/components/*"],
      "$components/*": ["./src/lib/components/*"]
    }
  },
  "exclude": [
    "./node_modules/**",
    "./.svelte-kit/**",
    "./dist/**",
    "./build/**",
    "./.svelte/**",
    "./.vercel_build_output/**",
    "./.vercel/**",
    "./coverage/**",
    "**/_/**"
  ]
}
```

### Logs : 

```
SvelteKitProject:build: error during build:
SvelteKitProject:build: Error: EPERM: operation not permitted, stat '[path]\TurboRepo\apps\SvelteKitProject\.svelte-kit\types\src\routes\$types.d.ts'
SvelteKitProject:build:     at Object.statSync (node:fs:1690:3)
SvelteKitProject:build:     at file:///[path]/TurboRepo/node_modules/.pnpm/@sveltejs+kit@1.25.1_svelte@4.2.1_vite@4.4.9/node_modules/@sveltejs/kit/src/core/sync/write_types/index.js:95:22
SvelteKitProject:build:     at Array.map (<anonymous>)
SvelteKitProject:build:     at write_all_types (file:///[path]/TurboRepo/node_modules/.pnpm/@sveltejs+kit@1.25.1_svelte@4.2.1_vite@4.4.9/node_modules/@sveltejs/kit/src/core/sync/write_types/index.js:94:27)
SvelteKitProject:build:     at create (file:///[path]/TurboRepo/node_modules/.pnpm/@sveltejs+kit@1.25.1_svelte@4.2.1_vite@4.4.9/node_modules/@sveltejs/kit/src/core/sync/sync.js:32:8)
SvelteKitProject:build:     at Module.all (file:///[path]/TurboRepo/node_modules/.pnpm/@sveltejs+kit@1.25.1_svelte@4.2.1_vite@4.4.9/node_modules/@sveltejs/kit/src/core/sync/sync.js:58:15)
SvelteKitProject:build:     at config (file:///[path]/TurboRepo/node_modules/.pnpm/@sveltejs+kit@1.25.1_svelte@4.2.1_vite@4.4.9/node_modules/@sveltejs/kit/src/exports/vite/index.js:298:34)
SvelteKitProject:build:     at runConfigHook (file:///[path]/TurboRepo/node_modules/.pnpm/vite@4.4.9_@types+node@18.17.1/node_modules/vite/dist/node/chunks/dep-df561101.js:66272:31)
SvelteKitProject:build:     at async resolveConfig (file:///[path]/TurboRepo/node_modules/.pnpm/vite@4.4.9_@types+node@18.17.1/node_modules/vite/dist/node/chunks/dep-df561101.js:65715:14)
SvelteKitProject:build:     at async build (file:///[path]/TurboRepo/node_modules/.pnpm/vite@4.4.9_@types+node@18.17.1/node_modules/vite/dist/node/chunks/dep-df561101.js:47852:20)
SvelteKitProject:build:  ELIFECYCLE  Command failed with exit code 1.
SvelteKitProject:build: ERROR: command finished with error: command ([path]\TurboRepo\apps\SvelteKitProject) pnpm run build exited (1)
SvelteKitProject#build: command ([path]\TurboRepo\apps\WingMan) pnpm run build exited (1)
```

### Expected Behavior

Should NOT have EPERM errors

### To Reproduce

```
npx turbo run dev --filter=SvelteKitProject --no-daemon --no-update-notifier

npx turbo run build --filter=SvelteKitProject --no-daemon --no-update-notifier
```

<sub>[TURBO-1439](https://linear.app/vercel/issue/TURBO-1439/[turborepo]-many-eperm-errors-on-turbo-sveltekit-dev-andand-build)</sub>

**Comment by chris-olszewski** [comment]
Have you attempted the [suggestion](https://github.com/sveltejs/kit/issues/10807#issuecomment-1755347933) made in the original issue? 

> test if it's turbo or not by running the build without turbo and seeing if that fixes it

If the path in question is covered by the `outputs` of a pipeline, then you could also try removing the path and running the command with `--force` to see if it is an issue with how we restore the file from cache.

This does appear to be something specific to your setup and I'll be unable to effectively help you without a reproduction repository.

**Comment by MarArMar** [comment]
The suggestion was posted after my issue

Will try it

**Comment by MarArMar** [comment]
Confirmed it was not a Turbo issue, reproduced the problem without it
