### ISSUE TITLE
[turborepo] Next.js 13.5.x applications fail to build from root mono repo

### ISSUE THREAD

**Issue by weyert** [vercel/turbo#6157]
### What version of Turborepo are you using?

1.10.15

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

I am having a Next.js web-application as a workspace in `pnpm` when I try to build the project with the command `ppm exec turbo run build --filter="webapp1" --force --no-cache`

I am getting errors for both the `/500` and `/404` page when run from the root of the mono repo:

```
webapp1:build: Error occurred prerendering page "/404". Read more: https://nextjs.org/docs/messages/prerender-error
webapp1:build: Error: NextRouter was not mounted. https://nextjs.org/docs/messages/next-router-not-mounted
webapp1:build:     at useRouter (/Users/weyert/Development/Projects/monorepo/projects/webapp1/build/server/chunks/6777.js:1:19620)
webapp1:build:     at __WEBPACK_DEFAULT_EXPORT__ (/Users/weyert/Development/Projects/monorepo/projects/webapp1/build/server/chunks/9178.js:6:19783)
webapp1:build:     at renderWithHooks (/Users/weyert/Development/Projects/monorepo/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5658:16)
webapp1:build:     at renderIndeterminateComponent (/Users/weyert/Development/Projects/monorepo/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5731:15)
webapp1:build:     at renderElement (/Users/weyert/Development/Projects/monorepo/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5946:7)
webapp1:build:     at renderNodeDestructiveImpl (/Users/weyert/Development/Projects/monorepo/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
webapp1:build:     at renderNodeDestructive (/Users/weyert/Development/Projects/monorepo/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
webapp1:build:     at renderIndeterminateComponent (/Users/weyert/Development/Projects/monorepo/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5785:7)
webapp1:build:     at renderElement (/Users/weyert/Development/Projects/monorepo/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5946:7)
webapp1:build:     at renderNodeDestructiveImpl (/Users/weyert/Development/Projects/monorepo/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
webapp1:build: Error: NextRouter was not mounted. https://nextjs.org/docs/messages/next-router-not-mounted
webapp1:build:     at useRouter (/Users/weyert/Development/Projects/monorepo/projects/webapp1/build/server/chunks/6777.js:1:19620)
webapp1:build:     at __WEBPACK_DEFAULT_EXPORT__ (/Users/weyert/Development/Projects/monorepo/projects/webapp1/build/server/chunks/9178.js:6:19783)
webapp1:build:     at renderWithHooks (/Users/weyert/Development/Projects/monorepo/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5658:16)
webapp1:build:     at renderIndeterminateComponent (/Users/weyert/Development/Projects/monorepo/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5731:15)
webapp1:build:     at renderElement (/Users/weyert/Development/Projects/monorepo/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5946:7)
webapp1:build:     at renderNodeDestructiveImpl (/Users/weyert/Development/Projects/monorepo/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
webapp1:build:     at renderNodeDestructive (/Users/weyert/Development/Projects/monorepo/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
webapp1:build:     at renderIndeterminateComponent (/Users/weyert/Development/Projects/monorepo/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5785:7)
webapp1:build:     at renderElement (/Users/weyert/Development/Projects/monorepo/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5946:7)
webapp1:build:     at renderNodeDestructiveImpl (/Users/weyert/Development/Projects/monorepo/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
webapp1:build:
```

while I run the command from the `projects/webapp1` directory/workspace the build succeeds and it does not complain about  or when I run `pnpm run build` from this directory it also succeeds.

The code of `/500` and `/404` doesn't use the `<Link>`-component or `useRouter`, for example, the contents for 404.tsx would be:

```typescript
import * as React from 'react'

function NotFoundPage() {
  return (
    <div className="flex flex-wrap content-center justify-center w-screen h-screen bg-indigo-600">
      <section className="px-4 py-8 text-center text-white">
        <div className="mx-auto max-w-auto">
          <h2 className="mt-8 text-xl font-medium lg:text-5xl">Oops!</h2>
          <p className="mt-6 text-sm lg:text-base">We can&rsquo;t seem to find the page you&rsquo;re looking for.</p>
          <p className="mt-4 text-sm">Error code: 404</p>
        </div>
        <div className="mt-8">
          <a
            href="/apps"
            className="p-3 rounded-lg border
             border-white hover:text-indigo-600 hover:bg-white"
          >
            Go back to the App
          </a>
        </div>
      </section>
    </div>
  )
}

export default NotFoundPage
```

### Expected Behavior

I would expect that a Next.js project compiles no matter how its being run 

### To Reproduce

Working on a repro

**Comment by weyert** [comment]
Everything works fine in the latest 13.4.x version but in that version I have issues with the optimising code for `@headless/ui` in the unit tests

**Comment by NicholasLYang** [comment]
Hey @weyert, thanks for the issue. Could you provide a dry run for both executions, i.e. the one that works and the one that doesn't? To do so, add `--dry-run json` to the command

**Comment by weyert** [comment]
@NicholasLYang Yes, sure, would you mind if I share them privately with you on Discord?

**Comment by NicholasLYang** [comment]
No problem! You can also email me at nicholas.yang@vercel.com

**Comment by weyert** [comment]
Figured it out! 

Apparently doing `NODE_ENV=development next build` breaks things

**Comment by Husain010** [comment]
@weyert Why does NODE_ENV cause the problem? Did you find the core reason for it?
