### ISSUE TITLE
Build command fails on create-turbo Yarn 4 project

### ISSUE THREAD

**Issue by MikelArnaiz** [vercel/turbo#6805]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

https://github.com/MikelArnaiz/turborepo-build-error-on-fresh-project

### What package manager are you using / does the bug impact?

Yarn v2/v3 (node_modules linker only)

### What operating system are you using?

Mac

### Which canary version will you have in your reproduction?

1.11.3-canary.0

### Describe the Bug

`yarn run build` fails on newly created project with `yarn dlx create-turbo@latest` (also `@canary`).

```
yarn build     
...
web:build: > Build error occurred
web:build: Error: Jest worker encountered 1 child process exceptions, exceeding retry limit
web:build:     at ChildProcessWorker.initialize (/Users/mikelarnaiz/projects/turbo/build-error-canary/.yarn/__virtual__/next-virtual-5514c12946/4/.yarn/berry/cache/next-npm-14.0.4-93c7e4ca0b-10c0.zip/node_modules/next/dist/compiled/jest-worker/index.js:1:11580)
web:build:     at ChildProcessWorker._onExit (/Users/mikelarnaiz/projects/turbo/build-error-canary/.yarn/__virtual__/next-virtual-5514c12946/4/.yarn/berry/cache/next-npm-14.0.4-93c7e4ca0b-10c0.zip/node_modules/next/dist/compiled/jest-worker/index.js:1:12545)
web:build:     at ChildProcess.emit (node:events:514:28)
web:build:     at ChildProcess._handle.onexit (node:internal/child_process:291:12) {
web:build:   type: 'WorkerError'
web:build: }
web:build: ERROR: command finished with error: command (/Users/mikelarnaiz/projects/turbo/build-error-canary/apps/web) /private/var/folders/1h/21ml03md75lcgwg74lj5nfmm0000gn/T/xfs-5c153812/yarn run build exited (1)
web#build: command (/Users/mikelarnaiz/projects/turbo/build-error-canary/apps/web) /private/var/folders/1h/21ml03md75lcgwg74lj5nfmm0000gn/T/xfs-5c153812/yarn run build exited (1)

 Tasks:    0 successful, 2 total
Cached:    0 cached, 2 total
  Time:    7.213s 
Failed:    web#build
```

### Expected Behavior

It should build. `yarn run dev` works as expected.

### To Reproduce

```
nvm use 18
cd ~
corepack enable
yarn set version 4.0.2
yarn -v // 4.0.2
yarn dlx create-turbo@canary // choose yarn
cd to directory
yarn run build // ERROR
```

Or 
- pull the repo https://github.com/MikelArnaiz/turborepo-build-error-on-fresh-project
- `yarn run build`

### Additional context

Is `yarn 4`, [released two months ago](https://yarnpkg.com/blog/release/4.0), not supported?

Is the missing `yarn 4` just needed to be updated?
![image](https://github.com/vercel/turbo/assets/2076221/a5f850ad-5ca2-46ee-bd0e-27cea9950217)

**Comment by anthonyshew** [comment]
@chris-olszewski Are we expected to have support here?

**Comment by anthonyshew** [comment]
I'm not certain what change fixed this since 2023, but this doesn't reproduce for me today with latest versions of Turborepo. If anyone reads this and is running into this still, please open a fresh issue and reproduction. Thanks!
