### ISSUE TITLE
Feature request: support ESM modules in turbo gen

### ISSUE THREAD

**Issue by CuriouslyCory** [vercel/turbo#7232]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

https://github.com/CuriouslyCory/turbo-gen-bug-example

### What package manager are you using / does the bug impact?

npm, pnpm

### What operating system are you using?

Windows

### Which canary version will you have in your reproduction?

turbo 1.12.2

### Describe the Bug

`turbo gen` fails with custom generators if `"type":"module"` is set in the app or packages `pacakge.json`

```bash
>>> Unexpected error. Please report it as a bug:
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: ~/workspace/test/turbo-gen-bug-example/apps/nextjs/turbo/generators/config.ts
require() of ES modules is not supported.
require() of ~/workspace/test/turbo-gen-bug-example/apps/nextjs/turbo/generators/config.ts from ~/.npm/_npx/111d46748c4e70c7/node_modules/node-plop/lib/node-plop.js is an ES module file as it is a .ts file whose nearest parent package.json contains "type": "module" which defines all .ts files in that package scope as ES modules.
Instead change the requiring code to use import(), or remove "type": "module" from ~/workspace/test/turbo-gen-bug-example/apps/nextjs/package.json.

    at createErrRequireEsm (~/.npm/_npx/111d46748c4e70c7/node_modules/ts-node/dist-raw/node-internal-errors.js:46:15)
    at assertScriptCanLoadAsCJSImpl (~/.npm/_npx/111d46748c4e70c7/node_modules/ts-node/dist-raw/node-internal-modules-cjs-loader.js:584:11)
    at Object.require.extensions.<computed> [as .ts] (~/.npm/_npx/111d46748c4e70c7/node_modules/ts-node/src/index.ts:1610:5)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at nodePlop (~/.npm/_npx/111d46748c4e70c7/node_modules/node-plop/lib/node-plop.js:297:28)
    at YC (~.npm/_npx/111d46748c4e70c7/node_modules/@turbo/gen/dist/cli.js:67:3474)
    at sm (~.npm/_npx/111d46748c4e70c7/node_modules/@turbo/gen/dist/cli.js:67:3687) {
  code: 'ERR_REQUIRE_ESM'
}
```

### Expected Behavior

`turbo gen` should correctly generate based on the template.

### To Reproduce

clone the repo @ https://github.com/CuriouslyCory/turbo-gen-bug-example
```bash
pnpm i
turbo gen some-example
```

Remove or comment the `"type":"module"` from apps/nextjs/package.json and test again to confirm this is the main cause of the issue.

### Additional context

This appears to be related to node-plop. Recent updates to node plop may resolve the issue but I was unable to successfully build the turbo cli from source to test.

This is how many new projects are configured including `create-t3-app` and it's child project `create-t3-turbo`.

**Comment by tknickman** [comment]
Hey @CuriouslyCory, this isn't supported right now, but it's on the list. Going close this one and keep https://github.com/vercel/turbo/issues/5657 as the main issue here.
