### ISSUE TITLE
`yarn create turbo` failing on `strict` windows

### ISSUE THREAD

**Issue by antokhio** [vercel/turbo#7880]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

`yarn create turbo`

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Windows

### Which canary version will you have in your reproduction?

can't init

### Describe the Bug

Hello, i'm trying to init turbo repo on some corporate laptop with some restricted policies, i'm getting this error:

```sh
>>> Unexpected error. Please report it as a bug:
Error: ENOENT: no such file or directory, open 'C:\Users\user\AppData\Roaming\turborepo\telemetry.json'
    at Object.openSync (node:fs:603:3)
    at readFileSync (node:fs:471:35)
    at xr.fromDefaultConfig (C:\Users\user\AppData\Local\Yarn\Data\global\node_modules\create-turbo\dist\cli.js:54:1346)
    at async Lm (C:\Users\user\AppData\Local\Yarn\Data\global\node_modules\create-turbo\dist\cli.js:54:6235)
    at async Object.callback (C:\Users\user\AppData\Local\Yarn\Data\global\node_modules\create-turbo\dist\cli.js:87:3415)
    at async Command.parseAsync (C:\Users\user\AppData\Local\Yarn\Data\global\node_modules\create-turbo\node_modules\commander\lib\command.js:935:5) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'C:\\Users\\user\\AppData\\Roaming\\turborepo\\telemetry.json'
}
```

Suspect the issue is it can't create telemetry.json without admin rights...

### Expected Behavior

turbo catches error

### To Reproduce

no clue really, seems needs Group Policy of some kind...

**Comment by arlyon** [comment]
Hi, thanks for the report. We are looking at this now.

**Comment by tknickman** [comment]
Patch should be available in around 20 minutes, I will update here when it's available. Thanks!
