### ISSUE TITLE
Unsupported URL Type "workspace:": workspace:* using npm or yarn

### ISSUE THREAD

**Issue by dead8309** [vercel/turbo#8208]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

npx create-turbo@latest -e with-docker

### What package manager are you using / does the bug impact?

npm, Yarn v1

### What operating system are you using?

Windows

### Which canary version will you have in your reproduction?

latest

### Describe the Bug

I'm not able to create a new project using `with-docker` template. 

Tested package managers:
- yarn
- npm

<details>
<summary>Yarn Logs</summary>

```
npx create-turbo@latest -e with-docker

>>> TURBOREPO

>>> Welcome to Turborepo! Let's get you set up with a new codebase.

? Where would you like to create your turborepo? ./test
? Which package manager do you want to use? yarn workspaces

Downloading files for example with-docker. This might take a moment.

>>> Created a new Turborepo with the following:

apps
 - apps/api
 - apps/web
packages
 - packages/eslint-config
 - packages/jest-presets
 - packages/logger
 - packages/typescript-config
 - packages/ui

Installing packages. This might take a couple of minutes.

    Installing dependencies...
>>> Unexpected error. Please report it as a bug:
Error: Command failed with exit code 1: yarn install
error Couldn't find package "@repo/eslint-config@workspace:*" required by "@repo/logger@0.0.0" on the "npm" registry.
Error: Couldn't find package "@repo/typescript-config@workspace:*" required by "@repo/logger@0.0.0" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/home/kiit/.nvm/versions/node/v20.13.1/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/home/kiit/.nvm/versions/node/v20.13.1/lib/node_modules/yarn/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/home/kiit/.nvm/versions/node/v20.13.1/lib/node_modules/yarn/lib/cli.js:36620:17)
    at Generator.throw (<anonymous>)
    at step (/home/kiit/.nvm/versions/node/v20.13.1/lib/node_modules/yarn/lib/cli.js:310:30)
    at /home/kiit/.nvm/versions/node/v20.13.1/lib/node_modules/yarn/lib/cli.js:323:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error: Couldn't find package "@repo/jest-presets@workspace:*" required by "@repo/logger@0.0.0" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/home/kiit/.nvm/versions/node/v20.13.1/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/home/kiit/.nvm/versions/node/v20.13.1/lib/node_modules/yarn/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/home/kiit/.nvm/versions/node/v20.13.1/lib/node_modules/yarn/lib/cli.js:36620:17)
    at Generator.throw (<anonymous>)
    at step (/home/kiit/.nvm/versions/node/v20.13.1/lib/node_modules/yarn/lib/cli.js:310:30)
    at /home/kiit/.nvm/versions/node/v20.13.1/lib/node_modules/yarn/lib/cli.js:323:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
yarn install v1.22.22
[1/5] Validating package.json...
[2/5] Resolving packages...
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
    at QB (/home/kiit/.npm/_npx/e8c68b66aeb1424f/node_modules/create-turbo/dist/cli.js:12:57)
    at /home/kiit/.npm/_npx/e8c68b66aeb1424f/node_modules/create-turbo/dist/cli.js:12:8077
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Fl (/home/kiit/.npm/_npx/e8c68b66aeb1424f/node_modules/create-turbo/dist/cli.js:60:2093)
    at async Command.y0 (/home/kiit/.npm/_npx/e8c68b66aeb1424f/node_modules/create-turbo/dist/cli.js:87:2121)
    at async Command.parseAsync (/home/kiit/.npm/_npx/e8c68b66aeb1424f/node_modules/commander/lib/command.js:936:5) {
  shortMessage: 'Command failed with exit code 1: yarn install',
  command: 'yarn install',
  escapedCommand: 'yarn install',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: 'yarn install v1.22.22\n' +
    '[1/5] Validating package.json...\n' +
    '[2/5] Resolving packages...\n' +
    'info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.',
  stderr: `error Couldn't find package "@repo/eslint-config@workspace:*" required by "@repo/logger@0.0.0" on the "npm" registry.\n` +
    `Error: Couldn't find package "@repo/typescript-config@workspace:*" required by "@repo/logger@0.0.0" on the "npm" registry.\n` +
    '    at MessageError.ExtendableBuiltin (/home/kiit/.nvm/versions/node/v20.13.1/lib/node_modules/yarn/lib/cli.js:721:66)\n' +
    '    at new MessageError (/home/kiit/.nvm/versions/node/v20.13.1/lib/node_modules/yarn/lib/cli.js:750:123)\n' +
    '    at PackageRequest.<anonymous> (/home/kiit/.nvm/versions/node/v20.13.1/lib/node_modules/yarn/lib/cli.js:36620:17)\n' +
    '    at Generator.throw (<anonymous>)\n' +
    '    at step (/home/kiit/.nvm/versions/node/v20.13.1/lib/node_modules/yarn/lib/cli.js:310:30)\n' +
    '    at /home/kiit/.nvm/versions/node/v20.13.1/lib/node_modules/yarn/lib/cli.js:323:13\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    `Error: Couldn't find package "@repo/jest-presets@workspace:*" required by "@repo/logger@0.0.0" on the "npm" registry.\n` +
    '    at MessageError.ExtendableBuiltin (/home/kiit/.nvm/versions/node/v20.13.1/lib/node_modules/yarn/lib/cli.js:721:66)\n' +
    '    at new MessageError (/home/kiit/.nvm/versions/node/v20.13.1/lib/node_modules/yarn/lib/cli.js:750:123)\n' +
    '    at PackageRequest.<anonymous> (/home/kiit/.nvm/versions/node/v20.13.1/lib/node_modules/yarn/lib/cli.js:36620:17)\n' +
    '    at Generator.throw (<anonymous>)\n' +
    '    at step (/home/kiit/.nvm/versions/node/v20.13.1/lib/node_modules/yarn/lib/cli.js:310:30)\n' +
    '    at /home/kiit/.nvm/versions/node/v20.13.1/lib/node_modules/yarn/lib/cli.js:323:13\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```
</details>

<details>
<summary>Npm Logs</summary>

```
npx create-turbo@latest -e with-docker

>>> TURBOREPO

>>> Welcome to Turborepo! Let's get you set up with a new codebase.

? Where would you like to create your turborepo? test2
? Which package manager do you want to use? npm workspaces

Downloading files for example with-docker. This might take a moment.

>>> Created a new Turborepo with the following:

apps
 - apps/api
 - apps/web
packages
 - packages/eslint-config
 - packages/jest-presets
 - packages/logger
 - packages/typescript-config
 - packages/ui

Installing packages. This might take a couple of minutes.

>>  Installing dependencies...
>>> Unexpected error. Please report it as a bug:
Error: Command failed with exit code 1: npm install
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "workspace:": workspace:*

npm ERR! A complete log of this run can be found in: /home/kiit/.npm/_logs/2024-05-23T19_49_35_228Z-debug-0.log
    at QB (/home/kiit/.npm/_npx/e8c68b66aeb1424f/node_modules/create-turbo/dist/cli.js:12:57)
    at /home/kiit/.npm/_npx/e8c68b66aeb1424f/node_modules/create-turbo/dist/cli.js:12:8077
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Fl (/home/kiit/.npm/_npx/e8c68b66aeb1424f/node_modules/create-turbo/dist/cli.js:60:2093)
    at async Command.y0 (/home/kiit/.npm/_npx/e8c68b66aeb1424f/node_modules/create-turbo/dist/cli.js:87:2121)
    at async Command.parseAsync (/home/kiit/.npm/_npx/e8c68b66aeb1424f/node_modules/commander/lib/command.js:936:5) {
  shortMessage: 'Command failed with exit code 1: npm install',
  command: 'npm install',
  escapedCommand: 'npm install',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: 'npm ERR! code EUNSUPPORTEDPROTOCOL\n' +
    'npm ERR! Unsupported URL Type "workspace:": workspace:*\n' +
    '\n' +
    'npm ERR! A complete log of this run can be found in: /home/kiit/.npm/_logs/2024-05-23T19_49_35_228Z-debug-0.log',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```
</details>

### Expected Behavior

A working project with no errors

### To Reproduce

```
npx create-turbo@latest -e with-docker
```

### Additional context

Ok so this error doesn't show up in canary version but canary is not respecting `-e with-docker` flag strange🤔

**Comment by anthonyshew** [comment]
The example was configured incorrectly and has now been fixed. Sorry about that, folks!
