### ISSUE TITLE
Linting plugin stopped working in 2.0.0-canary.0

### ISSUE THREAD

**Issue by weyert** [vercel/turbo#8252]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

n/a

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Which canary version will you have in your reproduction?

2.0.0-canary.0

### Describe the Bug

Upgrading `eslint-plugin-turbo` breaks/ stops the turbo lifting for functioning:

```bash
TypeError: Failed to load plugin 'turbo' declared in '--config » /Users/weyert/Development/Projects/company/company-monorepo/configs/eslint-config/turbo.js': Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at Ii.generateKey (/Users/weyert/Development/Projects/company/company-monorepo/node_modules/.pnpm/eslint-plugin-turbo@2.0.0-canary.0_eslint@8.57.0/node_modules/eslint-plugin-turbo/dist/index.js:74:6559)
    at new Ii (/Users/weyert/Development/Projects/company/company-monorepo/node_modules/.pnpm/eslint-plugin-turbo@2.0.0-canary.0_eslint@8.57.0/node_modules/eslint-plugin-turbo/dist/index.js:74:6200)
    at Object.<anonymous> (/Users/weyert/Development/Projects/company/company-monorepo/node_modules/.pnpm/eslint-plugin-turbo@2.0.0-canary.0_eslint@8.57.0/node_modules/eslint-plugin-turbo/dist/index.js:74:10209)
    at Module._compile (node:internal/modules/cjs/loader:1369:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Module._load (node:internal/modules/cjs/loader:1022:12)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at require (node:internal/modules/helpers:179:18)
```

### Expected Behavior

Able to use the `turbo` listing rules

### To Reproduce

Upgrade to Turbo v2 canary build and try to run the linting rules

### Additional context

Appears that code is still referring to `pipeline` instead of `tasks` when reading the turbo config file

**Comment by anthonyshew** [comment]
Looks like @chris-olszewski is ahead of it in #8253

**Comment by weyert** [comment]
Appears to fixed in the latest canary build

**Comment by anthonyshew** [comment]
That sounds similar to the error message I fixed in this PR: https://github.com/vercel/turbo/pull/8405

To be specific, renaming `eslint-config-turbo` to `turbo` in the ESLint configuration resolves that error.

**Comment by Grsz** [comment]
Still present, same error message
